import Head from "next/head";
import Orgsidebar from "@/components/organization/SideBar";
import Orgtopbar from "@/components/organization/TopBar";
import TeamMembers from "@/components/TeamMembers";
import { Listbox, Tab, Transition } from "@headlessui/react";
import { Fragment, useState } from "react";
import FormField from "@/components/FormField";
import Image from "next/image";
import userImg from 'public/images/user-image.png'
import socialIcon from 'public/images/social/linkedin-icon.png'
import Button from "@/components/Button";

const people = [
    { id: 1, name: 'Durward Reynolds', unavailable: false },
    { id: 2, name: 'Kenton Towne', unavailable: false },
    { id: 3, name: 'Therese Wunsch', unavailable: false },
    { id: 4, name: 'Benedict Kessler', unavailable: true },
    { id: 5, name: 'Katelyn Rohan', unavailable: false },
]

export default function OfferManagement() {
    const [selectedPerson, setSelectedPerson] = useState(people[0])
	return (
		<>
			<Head>
				<title>Offer Management</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<Orgsidebar />
				<Orgtopbar />
				<div id="overlay" className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"></div>
				<div className="layoutWrap">
                    <div className="flex flex-wrap items-center justify-between bg-white py-4 px-4 shadow-normal dark:bg-gray-800 lg:px-8">
						<div className="mr-3">
							<Listbox value={selectedPerson} onChange={setSelectedPerson}>
								<Listbox.Button className={"text-lg font-bold"}>
									{selectedPerson["name"]} <i className="fa-solid fa-chevron-down ml-2 text-sm"></i>
								</Listbox.Button>
								<Transition
									enter="transition duration-100 ease-out"
									enterFrom="transform scale-95 opacity-0"
									enterTo="transform scale-100 opacity-100"
									leave="transition duration-75 ease-out"
									leaveFrom="transform scale-100 opacity-100"
									leaveTo="transform scale-95 opacity-0"
								>
									<Listbox.Options
										className={
											"absolute left-0 top-[100%] mt-2 w-[250px] rounded-normal bg-white py-2 shadow-normal dark:bg-gray-700"
										}
									>
										{
                                            people.map((item) => (
												<Listbox.Option
													key={item.id}
													value={item}
													disabled={item.unavailable}
													className="clamp_1 relative cursor-pointer px-6 py-2 pl-8 text-sm hover:bg-gray-100 dark:hover:bg-gray-900"
												>
													{({ selected }) => (
														<>
															<span className={` ${selected ? "font-bold" : "font-normal"}`}>{item.name}</span>
															{selected ? (
																<span className="absolute left-3">
																	<i className="fa-solid fa-check"></i>
																</span>
															) : null}
														</>
													)}
												</Listbox.Option>
											))}
									</Listbox.Options>
								</Transition>
							</Listbox>
						</div>
						<aside className="flex items-center">
							<TeamMembers alen={'5'} />
						</aside>
					</div>
                    <div className="p-4 lg:p-8 flex flex-wrap">
                        <div className="w-full lg:max-w-[280px]">
                            <FormField
                                fieldType="input"
                                inputType="search"
                                placeholder="Search applicants, jobs ..."
                                icon={<i className="fa-solid fa-magnifying-glass"></i>}
                            />
                            <div>
                                {Array(10).fill(
                                <div className="mb-4 last:mb-0 rounded-normal bg-white dark:bg-gray-800 py-2 px-4 shadow-normal">
                                    <div className="mb-2 flex items-center justify-between">
                                        <aside className="flex items-center">
                                            <Image src={userImg} alt="User" width={30} className="h-[30px] rounded-full object-cover" />
                                            <h5 className="pl-4 text-sm font-semibold">
                                                Anne Jacobe
                                            </h5>
                                        </aside>
                                        <aside>
                                            <Image src={socialIcon} alt="Social" className="h-[16px] w-auto" />
                                        </aside>
                                    </div>
                                    <p className="mb-2 text-[12px] text-darkGray dark:text-gray-400">ID - 451295</p>
                                    <div className="flex items-center justify-between">
                                        <aside className="flex items-center text-[12px] text-darkGray dark:text-gray-400">
                                            <i className="fa-solid fa-calendar-days mr-2 text-[16px]"></i>
                                            <p>20 Jan 2021</p>
                                        </aside>
                                        <span className="text-darkGray dark:text-gray-400 text-[10px]">
                                            3:32 PM
                                        </span>
                                    </div>
                                </div> 
                                )}
                            </div>
                        </div>
                        <div className="w-full lg:max-w-[calc(100%-280px)] pl-6">
                            <div className="bg-white dark:bg-gray-800 rounded-normal border dark:border-gray-600">
                                <h2 className="font-bold text-xl px-10 py-4">Anne Jacobe</h2>
                                <Tab.Group>
                                    <Tab.List className={'px-10 border-b dark:border-b-gray-600'}>
                                        <Tab as={Fragment}>
											{({ selected }) => (
												<button
													className={
														"mr-6 border-b-4 py-3 font-semibold focus:outline-none" +
														" " +
														(selected
															? "border-primary text-primary"
															: "border-transparent text-darkGray dark:text-gray-400")
													}
												>
													Offer
												</button>
											)}
										</Tab>
                                        <Tab as={Fragment}>
											{({ selected }) => (
												<button
													className={
														"mr-6 border-b-4 py-3 font-semibold focus:outline-none" +
														" " +
														(selected
															? "border-primary text-primary"
															: "border-transparent text-darkGray dark:text-gray-400")
													}
												>
													Timeline
												</button>
											)}
										</Tab>
                                    </Tab.List>
                                    <Tab.Panels>
                                        <Tab.Panel>
                                            <div className="px-10 py-6">
                                                Steps
                                                <div className="flex flex-wrap -mx-3">
                                                    <div className="w-full md:max-w-[50%] px-3 mb-4">
                                                        <FormField label="Designation" fieldType="input" inputType="text" />
                                                    </div>
                                                    <div className="w-full md:max-w-[50%] px-3 mb-4">
                                                        <FormField label="Department" fieldType="input" inputType="text" />
                                                    </div>
                                                    <div className="w-full md:max-w-[50%] px-3 mb-4">
                                                        <FormField label="Section" fieldType="input" inputType="text" />
                                                    </div>
                                                    <div className="w-full md:max-w-[50%] px-3 mb-4">
                                                        <FormField label="Division" fieldType="input" inputType="text" />
                                                    </div>
                                                    <div className="w-full md:max-w-[50%] px-3 mb-4">
                                                        <FormField label="Grade" fieldType="input" inputType="text" />
                                                    </div>
                                                    <div className="w-full md:max-w-[50%] px-3 mb-4">
                                                        <FormField label="Location" fieldType="input" inputType="text" />
                                                    </div>
                                                </div>
                                                <div className="mb-4">
                                                    <h4 className="font-bold mb-2">Salary Range</h4>
                                                    <div className="flex flex-wrap">
                                                        <div className="w-[170px] pr-6 last:pr-0">
                                                            <FormField placeholder="Currency" fieldType="select" />
                                                        </div>
                                                        <div className="w-[170px] pr-6 last:pr-0">
                                                            <FormField placeholder="Monthly" fieldType="select" />
                                                        </div>
                                                        <div className="grow pr-6 last:pr-0">
                                                            <FormField placeholder="From" fieldType="input" inputType="number" />
                                                        </div>
                                                        <div className="grow pr-6 last:pr-0">
                                                            <FormField placeholder="To" fieldType="input" inputType="number" />
                                                        </div>
                                                    </div>
                                                </div>
                                                <FormField label="Candidate Type" fieldType="select" />
                                                <FormField label="Visa Sponsorship" fieldType="select" />
                                                <FormField label="Approval Authorities" fieldType="select" />
                                                <Button label="Send For Approval" />
                                            </div>
                                        </Tab.Panel>
                                        <Tab.Panel>
                                            B
                                        </Tab.Panel>
                                    </Tab.Panels>
                                </Tab.Group>
                            </div>
                        </div>
                    </div>
				</div>
			</main>
		</>
	);
}
