import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import Head from "next/head";
import { Tab } from "@headlessui/react";
import { Fragment, useState } from "react";
import FormField from "@/components/FormField";
import Image from "next/image";
import userImg from "/public/images/user-image.png";
import Button from "@/components/Button";

export default function Inbox() {
	const [togglePages, setTogglePages] = useState(true);
	function handleInboxPage() {
		setTogglePages(true);
	}
	function handleChatPage() {
		setTogglePages(false);
	}

	const MessageCards = () => {
		return (
			<>
				<div
					className={
						"flex border border-transparent border-b-slate-200 px-3 py-4 last:border-b-0 hover:shadow-highlight dark:border-b-gray-600 dark:hover:bg-gray-900"
					}
				>
					<Image
						src={userImg}
						alt="User"
						width={150}
						className="h-[50px] w-[50px] rounded-full object-cover shadow-highlight"
					/>
					<div className="w-[calc(100%-50px)] pt-1 pl-3">
						<div className="mb-2 flex justify-between">
							<h5 className="text-sm font-semibold">Jack Paul</h5>
							<span className="block rounded bg-gray-200 py-1 px-2 text-[10px] font-semibold dark:bg-gray-600">
								3:30 PM
							</span>
						</div>
						<p className="clamp_2 text-[12px] text-darkGray">
							Your Interview has been scheduled for Software Developer Job at Organization Name Software Developer Job
							at Organization Name
						</p>
					</div>
				</div>
			</>
		);
	};

	return (
		<>
			<Head>
				<title>Inbox</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<OrgSideBar />
				<OrgTopBar />
				<div
					id="overlay"
					className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"
				></div>
				<div className="layoutWrap p-4 lg:p-8">
					<div className="flex flex-wrap">
						<div className="w-full md:max-w-[32%]">
							<div className="rounded-normal border bg-white shadow-normal overflow-hidden dark:border-gray-600 dark:bg-gray-800">
								<Tab.Group>
									<Tab.List className={"border-b px-6 pt-2 dark:border-gray-600"}>
										<Tab as={Fragment}>
											{({ selected }) => (
												<button
													className={
														"mr-6 border-b-4 py-3 font-semibold focus:outline-none" +
														" " +
														(selected
															? "border-primary text-primary"
															: "border-transparent text-darkGray dark:text-gray-400")
													}
													onClick={() => handleInboxPage()}
												>
													Inbox
												</button>
											)}
										</Tab>
										<Tab as={Fragment}>
											{({ selected }) => (
												<button
													className={
														"mr-6 border-b-4 py-3 font-semibold focus:outline-none" +
														" " +
														(selected
															? "border-primary text-primary"
															: "border-transparent text-darkGray dark:text-gray-400")
													}
													onClick={() => handleChatPage()}
												>
													Chats
												</button>
											)}
										</Tab>
									</Tab.List>
									<Tab.Panels>
										<Tab.Panel>
											<Tab.Group>
												<Tab.List className={"px-6"}>
													<Tab as={Fragment}>
														{({ selected }) => (
															<button
																className={
																	"mr-6 py-3 text-sm font-semibold focus:outline-none" +
																	" " +
																	(selected ? "text-primary" : "text-darkGray dark:text-gray-400")
																}
															>
																Applicants
															</button>
														)}
													</Tab>
													<Tab as={Fragment}>
														{({ selected }) => (
															<button
																className={
																	"mr-6 py-3 text-sm font-semibold focus:outline-none" +
																	" " +
																	(selected ? "text-primary" : "text-darkGray dark:text-gray-400")
																}
															>
																Vendors
															</button>
														)}
													</Tab>
												</Tab.List>
												<Tab.Panels>
													<Tab.Panel>
														<div className="p-4 pt-0">
															<FormField
																fieldType="input"
																inputType="search"
																placeholder="Search applicants"
																icon={<i className="fa-solid fa-magnifying-glass"></i>}
															/>
														</div>
														<div className="h-[calc(100vh-300px)] overflow-y-auto p-4 pt-0">
															{Array(5).fill(<MessageCards />)}
														</div>
													</Tab.Panel>
													<Tab.Panel>
														<div className="p-4 pt-0">
															<FormField
																fieldType="input"
																inputType="search"
																placeholder="Search vendors"
																icon={<i className="fa-solid fa-magnifying-glass"></i>}
															/>
														</div>
														<div className="h-[calc(100vh-300px)] overflow-y-auto p-4 pt-0">
															{Array(5).fill(<MessageCards />)}
														</div>
													</Tab.Panel>
												</Tab.Panels>
											</Tab.Group>
										</Tab.Panel>
										<Tab.Panel>
											<Tab.Group>
												<Tab.List className={"px-6"}>
													<Tab as={Fragment}>
														{({ selected }) => (
															<button
																className={
																	"mr-6 py-3 text-sm font-semibold focus:outline-none" +
																	" " +
																	(selected ? "text-primary" : "text-darkGray dark:text-gray-400")
																}
															>
																Team
															</button>
														)}
													</Tab>
													<Tab as={Fragment}>
														{({ selected }) => (
															<button
																className={
																	"mr-6 py-3 text-sm font-semibold focus:outline-none" +
																	" " +
																	(selected ? "text-primary" : "text-darkGray dark:text-gray-400")
																}
															>
																Vendors
															</button>
														)}
													</Tab>
												</Tab.List>
												<Tab.Panels>
													<Tab.Panel>
														<div className="p-4 pt-0">
															<FormField
																fieldType="input"
																inputType="search"
																placeholder="Search team"
																icon={<i className="fa-solid fa-magnifying-glass"></i>}
															/>
														</div>
														<div className="h-[calc(100vh-300px)] overflow-y-auto p-4 pt-0">
															{Array(5).fill(<MessageCards />)}
														</div>
													</Tab.Panel>
													<Tab.Panel>
														<div className="p-4 pt-0">
															<FormField
																fieldType="input"
																inputType="search"
																placeholder="Search vendors"
																icon={<i className="fa-solid fa-magnifying-glass"></i>}
															/>
														</div>
														<div className="h-[calc(100vh-300px)] overflow-y-auto p-4 pt-0">
															{Array(5).fill(<MessageCards />)}
														</div>
													</Tab.Panel>
												</Tab.Panels>
											</Tab.Group>
										</Tab.Panel>
									</Tab.Panels>
								</Tab.Group>
							</div>
						</div>
						<div className="w-full pl-6 md:max-w-[68%]">
							<div className="relative pb-[80px] shadow-normal h-full overflow-hidden rounded-normal border bg-white dark:border-gray-600 dark:bg-gray-700">
								{togglePages ? (
									<>
                                        <div className="h-[calc(100vh-212px)] overflow-y-auto">
                                            <div className="group">
                                                <div className="py-6 px-4 border-b dark:border-b-gray-600 group-last:border-b-0">
                                                    <div className="mx-auto w-full max-w-[90%]">
                                                        <div className="flex items-center justify-between mb-4">
                                                            <Image
                                                                src={userImg}
                                                                alt="User"
                                                                width={150}
                                                                className="h-[50px] w-[50px] rounded-full object-cover shadow-highlight"
                                                            />
                                                            <p className="text-right text-[12px] text-darkGray dark:text-gray-400">
                                                                10 Feb 2023
                                                                <br />
                                                                3:30 PM
                                                            </p>
                                                        </div>
                                                        <article className="text-sm text-darkGray dark:text-gray-400">
                                                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. 
                                                        It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
                                                        </article>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="group">
                                                <div className="py-6 px-4 border-b dark:border-b-gray-600 group-last:border-b-0">
                                                    <div className="mx-auto w-full max-w-[90%]">
                                                        <div className="border dark:border-gray-500 rounded-large overflow-hidden">
                                                            <div className="bg-gradient-to-b from-gradLightBlue to-gradDarkBlue p-6 text-center text-white">
                                                                <h3 className="text-xl mb-2">Interview has been Scheduled</h3>
                                                                <p>You can find the details below</p>
                                                            </div>
                                                            <div className="py-6 px-10">
                                                                <h2 className="font-bold text-lg mb-4">Hi Recruiter Name,</h2>
                                                                <p className="text-sm text-darkGray dark:text-gray-400 mb-6">Your Interview has been scheduled for Software Developer Job at Organization Name</p>
                                                                <div className="flex flex-wrap mb-2">
                                                                    <div className="w-full md:max-w-[75%]">
                                                                        <ul>
                                                                            <li className="flex items-start mb-6">
                                                                                <span className="mr-4 inline-block w-30px">
                                                                                    <i className="fa-solid fa-user text-[14px]"></i>
                                                                                </span>
                                                                                <aside className="grow">
                                                                                    <h5 className="font-bold">Interviewer</h5>
                                                                                    <p className="text-sm text-darkGray dark:text-gray-400">Adam Smith</p>
                                                                                </aside> 
                                                                            </li>
                                                                            <li className="flex items-start mb-6">
                                                                                <span className="mr-4 inline-block w-30px">
                                                                                    <i className="fa-solid fa-street-view text-[14px]"></i>
                                                                                </span>
                                                                                <aside className="grow">
                                                                                    <h5 className="font-bold">Interview Name</h5>
                                                                                    <p className="text-sm text-darkGray dark:text-gray-400">Software Developer</p>
                                                                                </aside> 
                                                                            </li>
                                                                            <li className="flex items-start mb-6">
                                                                                <span className="mr-4 inline-block w-30px">
                                                                                    <i className="fa-solid fa-clock text-[14px]"></i>
                                                                                </span>
                                                                                <aside className="grow">
                                                                                    <h5 className="font-bold">Event Duration</h5>
                                                                                    <p className="text-sm text-darkGray dark:text-gray-400">30 min</p>
                                                                                </aside> 
                                                                            </li>
                                                                        </ul>
                                                                    </div>
                                                                    <div className="w-full md:max-w-[25%]">
                                                                        <aside className="flex items-center mb-6">
                                                                            <h5 className="font-bold mr-4">Date:</h5>
                                                                            <p className="text-sm text-darkGray dark:text-gray-400">05 Dec 2022</p>
                                                                        </aside> 
                                                                        <aside className="flex items-center mb-4">
                                                                            <h5 className="font-bold mr-4">Time:</h5>
                                                                            <p className="text-sm text-darkGray dark:text-gray-400">02:00 PM</p>
                                                                        </aside> 
                                                                    </div>
                                                                </div>
                                                                <div className="flex flex-wrap">
                                                                    <div className="my-1 mr-4 last:mr-0">
                                                                        <Button btnStyle="success" label="Reschedule" />
                                                                    </div>
                                                                    <div className="my-1 mr-4 last:mr-0">
                                                                        <Button btnStyle="danger" label="Cancel" />
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="absolute left-0 bottom-0 w-full bg-lightBlue p-3 border-t dark:border-t-gray-600 dark:bg-gray-900">
                                            <div className="flex items-center rounded bg-white p-2 shadow-normal dark:bg-gray-800">
                                                <textarea
                                                    name=""
                                                    id=""
                                                    className="h-[40px] w-[calc(100%-50px)] resize-none  border-0 bg-transparent focus:border-0 focus:shadow-none focus:outline-none focus:ring-0"
                                                    placeholder="Type something..."
                                                ></textarea>
                                                <button
                                                    type="button"
                                                    className="block w-[50px] border-l-2 border-gray-400 text-sm leading-normal"
                                                >
                                                    <i className="fa-solid fa-paper-plane"></i>
                                                </button>
                                            </div>
                                        </div>
									</>
								) : (
									<>Chat Page</>
								)}
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
