import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import userIcon from "/public/images/icons/user.png";
import integrationIcon from "/public/images/icons/integration.png";
import vendorsIcon from "/public/images/icons/vendors.png";
import calendarIcon from "/public/images/icons/calendar.png";
import teamUsersIcon from "/public/images/icons/team-users.png";
import bellIcon from "/public/images/icons/bell.png";

export default function Settings() {
    const quicklinks = [
		{
			name: "Profile",
			icon: userIcon,
			link: "/organization/settings/profile"
		},
		{
			name: "Integrations",
			icon: integrationIcon,
			link: "/organization/settings/integrations"
		},
		{
			name: "Vendors",
			icon: vendorsIcon,
			link: "#"
		},
		{
			name: "Calendar",
			icon: calendarIcon,
			link: "/organization/settings/calendar"
		},
		{
			name: "Team Members",
			icon: teamUsersIcon,
			link: "/organization/settings/team-members"
		},
		{
			name: "Notifications",
			icon: bellIcon,
			link: "/organization/settings/notifications"
		}
	];
    return (
        <>
            <Head>
				<title>Settings</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<OrgSideBar />
				<OrgTopBar />
				<div id="overlay" className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"></div>
				<div className="layoutWrap p-4 lg:p-8">
                    <div className="relative bg-white dark:bg-gray-800 rounded-normal shadow-normal p-10">
						<h1 className="font-bold text-2xl mb-6">Settings</h1>
						<div className="flex flex-wrap items-center -mx-4">
							{quicklinks.map((links, i) => (
								<div key={i} className="mb-8 w-full px-4 md:max-w-[50%] lg:max-w-[25%]">
									<Link
										href={links.link}
										className="block rounded-normal bg-white p-6 shadow-normal hover:bg-lightBlue dark:bg-gray-700 dark:hover:bg-gray-600"
									>
										<div className="flex w-full items-center mb-10">
											<div className="mr-4 flex h-[45px] w-[45px] items-center justify-center rounded bg-[#B2E3FF] p-3">
												<Image src={links.icon} alt={links.name} width={100} />
											</div>
											<span className="text-lg font-bold">{links.name}</span>
										</div>
										<span className="text-primary dark:text-gray-300 text-sm flex items-center">Go To <i className="fa-solid fa-arrow-right text-[12px] ml-2"></i></span>
									</Link>
								</div>
							))}
						</div>
					</div>
                </div>
            </main>
        </>
    )
}