import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { Menu, Tab, Transition } from "@headlessui/react";
import pricingIcon from '/public/images/icons/pricing.png'
import { Fragment } from "react";
import Button from "@/components/Button";

export default function Pricing() {
    const router = useRouter();
    const tabHeading_1 = [
        {
            title: 'Monthly'
        },
        {
            title: 'Yearly'
        }
    ]
    return(
        <>
            <Head>
				<title>Plans and Pricing</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<OrgSideBar />
				<OrgTopBar />
				<div id="overlay" className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"></div>
				<div className="layoutWrap p-4 lg:p-8">
                    <div className="rounded-normal bg-white shadow-normal dark:bg-gray-800">
						<div className="border-b py-4">
                            <div className="w-full max-w-[1100px] mx-auto flex flex-wrap items-center justify-start py-2 px-4">
                                <button
                                    onClick={() => router.back()}
                                    className="mr-10 justify-self-start text-darkGray dark:text-gray-400"
                                >
                                    <i className="fa-solid fa-arrow-left text-2xl"></i>
                                </button>
                                <h2 className="text-xl font-bold flex items-center">
                                    <div className="mr-4 flex h-[45px] w-[45px] items-center justify-center rounded bg-[#B2E3FF] p-3">
                                        <Image src={pricingIcon} alt='Active Job' height={20} />
                                    </div>
                                    <span>Plans and Pricing</span>
                                </h2>
                            </div>
						</div>
                        <div className="w-full max-w-[980px] mx-auto px-4 py-6">
                            <div className="w-full max-w-[800px] mx-auto lg:mb-[-40px]">
                                <p className="text-darkGray dark:text-gray-400 font-semibold text-sm w-[60%]">
                                Whether your time-saving automation needs are large or small, we are here to help you scale.
                                </p>
                            </div>
                            <Tab.Group>
                                <Tab.List className={"text-right w-full max-w-[800px] mx-auto mb-10"}>
                                    {tabHeading_1.map((item, i)=> 
                                    <Tab key={i} as={Fragment}>
                                        {({ selected }) => (
                                            <button
                                                className={
                                                    "py-2 px-4 rounded-full text-[12px] uppercase font-bold" +
                                                    " " +
                                                    (selected ? "text-white bg-primary" : "text-darkGray dark:text-gray-400")
                                                }
                                            >
                                                {item.title}
                                            </button>
                                        )}
                                    </Tab>
                                    )}
                                </Tab.List>
                                <Tab.Panels>
                                    <Tab.Panel>
                                        <div className="w-full max-w-[800px] mx-auto flex flex-wrap mb-6">
                                            <div className="w-full md:max-w-[50%] lg:max-w-[calc(100%/3)] px-3 mb-4">
                                                <div className="bg-white dark:bg-gray-600 text-darkGray rounded-normal p-4 dark:text-gray-400 text-sm">
                                                    <div className="text-right mb-10">
                                                        
                                                    </div>
                                                    <h3 className="font-extrabold text-2xl mb-3 text-black dark:text-white">
                                                        $19
                                                        <sub className="text-sm text-darkGray dark:text-gray-400 bottom-0"> / month</sub>
                                                    </h3>
                                                    <h5 className="text-xl font-semibold mb-2 text-black dark:text-white">Starter</h5>
                                                    <p className="text-[12px] mb-2">Unleash the power of automation.</p>
                                                    <ul className="mb-[92px]">
                                                        {Array(2).fill(
                                                        <li className="my-3 flex items-center">
                                                            <i className="fa-solid fa-circle-check mr-2"></i>
                                                            Lorem Impsum text editor
                                                        </li>
                                                        )}
                                                    </ul>
                                                    <div className="text-center">
                                                        <Button btnStyle="gray" label="Choose Plan" full />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="w-full md:max-w-[50%] lg:max-w-[calc(100%/3)] px-3 mb-4">
                                                <div className="bg-white dark:bg-gray-600 text-darkGray rounded-normal p-4 dark:text-gray-400 text-sm">
                                                    <div className="text-right mb-10">
                                                        
                                                    </div>
                                                    <h3 className="font-extrabold text-2xl mb-3 text-black dark:text-white">
                                                        $54
                                                        <sub className="text-sm text-darkGray dark:text-gray-400 bottom-0"> / month</sub>
                                                    </h3>
                                                    <h5 className="text-xl font-semibold mb-2 text-black dark:text-white">Premium</h5>
                                                    <p className="text-[12px] mb-2">Advanced tools to take your work to the next level.</p>
                                                    <ul className="mb-10">
                                                        {Array(3).fill(
                                                        <li className="my-3 flex items-center">
                                                            <i className="fa-solid fa-circle-check mr-2"></i>
                                                            Lorem Impsum text editor
                                                        </li>
                                                        )}
                                                    </ul>
                                                    <div className="text-center">
                                                        <Button btnStyle="gray" label="Choose Plan" full />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="w-full md:max-w-[50%] lg:max-w-[calc(100%/3)] px-3 mb-4">
                                                <div className="bg-gradient-to-b from-gradLightBlue to-gradDarkBlue rounded-normal p-4 text-white text-sm shadow-highlight">
                                                    <div className="text-right mb-4">
                                                        <span className="rounded-full bg-[#403879] text-white py-1 px-4 font-bold text-[10px] uppercase">Most Popular</span>
                                                    </div>
                                                    <h3 className="font-extrabold text-2xl mb-3">Book</h3>
                                                    <h5 className="text-xl font-semibold mb-2">Enterprise</h5>
                                                    <p className="text-[12px] mb-2">Automation plus enterprise-grade features.</p>
                                                    <ul>
                                                        {Array(4).fill(
                                                        <li className="my-3 flex items-center">
                                                            <i className="fa-solid fa-circle-check mr-2"></i>
                                                            Lorem Impsum text editor
                                                        </li>
                                                        )}
                                                    </ul>
                                                    <div className="text-center">
                                                        <Button label="Request a Call" full />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div>
                                            <table cellPadding={"0"} cellSpacing={"0"} className="w-full">
                                                <thead>
                                                    <tr>
                                                        <th className="border-b py-2 px-3 w-[300px]">

                                                        </th>
                                                        <th className="border-b py-2 px-3">
                                                            Starter
                                                        </th>
                                                        <th className="border-b py-2 px-3">
                                                            Premium
                                                        </th>
                                                        <th className="border-b py-2 px-3">
                                                            Enterprises
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody className="text-sm font-semibold">
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Members
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            1
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Up to 3
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Unlimited
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Workspace roles
                                                            <span className="inline-block border border-darkGray text-[10px] text-darkGray leading-normal rounded-full px-1 ml-2 dark:bg-gray-200">soon</span>
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Lorem
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Lorem
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Lorem
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Guests
                                                            <span className="inline-block border border-darkGray text-[10px] text-darkGray leading-normal rounded-full px-1 ml-2 dark:bg-gray-200">soon</span>
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Live Collaboration
                                                            <span className="inline-block border border-darkGray text-[10px] text-darkGray leading-normal rounded-full px-1 ml-2 dark:bg-gray-200">soon</span>
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Integration of sub-brands
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Access to standard templates
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Access to pro templates
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Custom designed templates
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Asset library
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </Tab.Panel>
                                    <Tab.Panel>
                                        <div className="w-full max-w-[800px] mx-auto flex flex-wrap mb-6">
                                            <div className="w-full md:max-w-[50%] lg:max-w-[calc(100%/3)] px-3 mb-4">
                                                <div className="bg-white dark:bg-gray-600 text-darkGray rounded-normal p-4 dark:text-gray-400 text-sm">
                                                    <div className="text-right mb-10">
                                                        
                                                    </div>
                                                    <h3 className="font-extrabold text-2xl mb-3 text-black dark:text-white">
                                                        $229
                                                        <sub className="text-sm text-darkGray dark:text-gray-400 bottom-0"> / yearly</sub>
                                                    </h3>
                                                    <h5 className="text-xl font-semibold mb-2 text-black dark:text-white">Starter</h5>
                                                    <p className="text-[12px] mb-2">Unleash the power of automation.</p>
                                                    <ul className="mb-[92px]">
                                                        {Array(2).fill(
                                                        <li className="my-3 flex items-center">
                                                            <i className="fa-solid fa-circle-check mr-2"></i>
                                                            Lorem Impsum text editor
                                                        </li>
                                                        )}
                                                    </ul>
                                                    <div className="text-center">
                                                        <Button btnStyle="gray" label="Choose Plan" full />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="w-full md:max-w-[50%] lg:max-w-[calc(100%/3)] px-3 mb-4">
                                                <div className="bg-white dark:bg-gray-600 text-darkGray rounded-normal p-4 dark:text-gray-400 text-sm">
                                                    <div className="text-right mb-10">
                                                        
                                                    </div>
                                                    <h3 className="font-extrabold text-2xl mb-3 text-black dark:text-white">
                                                        $454
                                                        <sub className="text-sm text-darkGray dark:text-gray-400 bottom-0"> / yearly</sub>
                                                    </h3>
                                                    <h5 className="text-xl font-semibold mb-2 text-black dark:text-white">Premium</h5>
                                                    <p className="text-[12px] mb-2">Advanced tools to take your work to the next level.</p>
                                                    <ul className="mb-10">
                                                        {Array(3).fill(
                                                        <li className="my-3 flex items-center">
                                                            <i className="fa-solid fa-circle-check mr-2"></i>
                                                            Lorem Impsum text editor
                                                        </li>
                                                        )}
                                                    </ul>
                                                    <div className="text-center">
                                                        <Button btnStyle="gray" label="Choose Plan" full />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="w-full md:max-w-[50%] lg:max-w-[calc(100%/3)] px-3 mb-4">
                                                <div className="bg-gradient-to-b from-gradLightBlue to-gradDarkBlue rounded-normal p-4 text-white text-sm shadow-highlight">
                                                    <div className="text-right mb-4">
                                                        <span className="rounded-full bg-[#403879] text-white py-1 px-4 font-bold text-[10px] uppercase">Most Popular</span>
                                                    </div>
                                                    <h3 className="font-extrabold text-2xl mb-3">Book</h3>
                                                    <h5 className="text-xl font-semibold mb-2">Enterprise</h5>
                                                    <p className="text-[12px] mb-2">Automation plus enterprise-grade features.</p>
                                                    <ul>
                                                        {Array(4).fill(
                                                        <li className="my-3 flex items-center">
                                                            <i className="fa-solid fa-circle-check mr-2"></i>
                                                            Lorem Impsum text editor
                                                        </li>
                                                        )}
                                                    </ul>
                                                    <div className="text-center">
                                                        <Button label="Request a Call" full />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div>
                                            <table cellPadding={"0"} cellSpacing={"0"} className="w-full">
                                                <thead>
                                                    <tr>
                                                        <th className="border-b py-2 px-3 w-[300px]">

                                                        </th>
                                                        <th className="border-b py-2 px-3">
                                                            Starter
                                                        </th>
                                                        <th className="border-b py-2 px-3">
                                                            Premium
                                                        </th>
                                                        <th className="border-b py-2 px-3">
                                                            Enterprises
                                                        </th>
                                                    </tr>
                                                </thead>
                                                <tbody className="text-sm font-semibold">
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Members
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            1
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Up to 3
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Unlimited
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Workspace roles
                                                            <span className="inline-block border border-darkGray text-[10px] text-darkGray leading-normal rounded-full px-1 ml-2 dark:bg-gray-200">soon</span>
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Lorem
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Lorem
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            Lorem
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Guests
                                                            <span className="inline-block border border-darkGray text-[10px] text-darkGray leading-normal rounded-full px-1 ml-2 dark:bg-gray-200">soon</span>
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Live Collaboration
                                                            <span className="inline-block border border-darkGray text-[10px] text-darkGray leading-normal rounded-full px-1 ml-2 dark:bg-gray-200">soon</span>
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Integration of sub-brands
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Access to standard templates
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Access to pro templates
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Custom designed templates
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                    <tr className="odd:bg-gray-100 dark:odd:bg-gray-600">
                                                        <td className="py-2 px-3 w-[300px]">
                                                            Asset library
                                                            <Menu as="div" className="relative inline-block">
                                                                <Menu.Button className="ml-2 w-6 py-2 text-darkGray dark:text-gray-400">
                                                                    <i className="fa-solid fa-circle-question"></i>
                                                                </Menu.Button>
                                                                <Transition
                                                                as={Fragment}
                                                                enter="transition ease-out duration-100"
                                                                enterFrom="transform opacity-0 scale-95"
                                                                enterTo="transform opacity-100 scale-100"
                                                                leave="transition ease-in duration-75"
                                                                leaveFrom="transform opacity-100 scale-100"
                                                                leaveTo="transform opacity-0 scale-95"
                                                                >
                                                                    <Menu.Items className={'absolute z-[2] left-[100%] top-0 text-white bg-gradDarkBlue w-[200px] rounded py-2 px-4 text-[10px] leading-normal shadow-highlight ml-2'}>
                                                                        <span className="bg-gradDarkBlue absolute w-3 h-3 block -left-1 top-4 rotate-45"></span>
                                                                        <Menu.Item>
                                                                            <p>Lorem impsum is a dummy text provide here.</p>
                                                                        </Menu.Item>
                                                                    </Menu.Items>
                                                                </Transition>
                                                            </Menu>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                        <td className="py-2 px-3 text-center">
                                                            <i className="fa-solid fa-check"></i>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </Tab.Panel>
                                </Tab.Panels>
                            </Tab.Group>
                        </div>
					</div>
                </div>
            </main>
        </>
    )
}