import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import Head from "next/head";
import { Dialog, Listbox, Tab, Transition } from "@headlessui/react";
import { useRouter } from "next/router";
import Image from "next/image";
import usersIcon from "/public/images/icons/team-users.png";
import { Fragment, useRef, useState } from "react";
import FormField from "@/components/FormField";
import Button from "@/components/Button";

const people = [
    { name: 'Recruiter' },
    { name: 'Collaborator' },
    { name: 'Hiring Manager' }
  ]

export default function TeamMembers() {
    const router = useRouter();

    const [access, setAccess] = useState(people[0])

    const cancelButtonRef = useRef(null);
    const [addGroups, setAddGroups] = useState(false);

    const tabHeading_1 = [
        {
            title: 'All Team Members'
        },
        {
            title: 'Division'
        }
    ]
    const TeamTableHead = [
		{
			title: "User Name"
		},
		{
			title: "Department/Title"
		},
		{
			title: "Email"
		},
        {
			title: "Invite Status"
		},
		{
			title: "Access"
		},
		{
			title: " "
		}
	];
    return(
        <>
            <Head>
				<title>Team Members</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<OrgSideBar />
				<OrgTopBar />
				<div id="overlay" className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"></div>
				<div className="layoutWrap p-4 lg:p-8">
                    <div className="rounded-normal bg-white shadow-normal dark:bg-gray-800">
						<div className="py-4">
                            <div className="w-full max-w-[1100px] mx-auto mb-4 flex flex-wrap items-center justify-start py-2 px-4">
                                <button
                                    onClick={() => router.back()}
                                    className="mr-10 justify-self-start text-darkGray dark:text-gray-400"
                                >
                                    <i className="fa-solid fa-arrow-left text-2xl"></i>
                                </button>
                                <h2 className="text-xl font-bold flex items-center">
                                    <div className="mr-4 flex h-[45px] w-[45px] items-center justify-center rounded bg-[#B2E3FF] p-3">
                                        <Image src={usersIcon} alt='Active Job' height={20} />
                                    </div>
                                    <span>Team Members</span>
                                </h2>
                            </div>
                            <Tab.Group>
                                <div className={"border-b px-4"}>
                                    <Tab.List className={"w-full max-w-[950px] mx-auto"}>
                                        {tabHeading_1.map((item, i)=> 
                                        <Tab key={i} as={Fragment}>
                                            {({ selected }) => (
                                                <button
                                                    className={
                                                        "border-b-4 py-2 mr-16 font-semibold focus:outline-none" +
                                                        " " +
                                                        (selected ? "border-primary text-primary" : "border-transparent text-darkGray dark:text-gray-400")
                                                    }
                                                >
                                                    {item.title}
                                                </button>
                                            )}
                                        </Tab>
                                        )}
                                    </Tab.List>
                                </div>
                                <Tab.Panels className={"w-full max-w-[980px] mx-auto px-4 py-8"}>
                                    <Tab.Panel>
                                        <div className="mb-6 flex flex-wrap items-center justify-between">
											<div className="w-[350px] pr-2">
												<FormField
													fieldType="input"
													inputType="search"
													placeholder="Search"
													icon={<i className="fa-solid fa-magnifying-glass"></i>}
												/>
											</div>
											<div className="flex grow items-center justify-end">
                                                <div className="mr-3">
                                                    <button className="bg-gradient-to-b from-gradLightBlue to-gradDarkBlue py-2 px-4 rounded-normal text-white text-lg" onClick={() => setAddGroups(true)}>
                                                        <i className="fa-solid fa-plus"></i>
                                                    </button>
                                                </div>
                                                <div className="mr-3 w-[150px]">
													<FormField
														fieldType="select"
														placeholder="Sort"
														singleSelect={true}
														options={[
															{
																id: "A-to-Z",
																name: "A to Z"
															},
															{
																id: "Z-to-A",
																name: "Z to A"
															}
														]}
													/>
												</div>
												<div className="w-[150px]">
													<label
														htmlFor="teamSelectAll"
														className="flex min-h-[45px] w-full cursor-pointer items-center justify-between rounded-normal border border-borderColor p-3 text-sm text-darkGray dark:bg-gray-700 dark:border-gray-600"
													>
														<span>Select All</span>
														<input type="checkbox" id="teamSelectAll" />
													</label>
												</div>
											</div>
										</div>
										<div className="overflow-x-auto">
											<table cellPadding={"0"} cellSpacing={"0"} className="w-full">
												<thead>
													<tr>
														{TeamTableHead.map((item, i) => (
															<th className="border-b py-2 px-3 text-left" key={i}>
																{item.title}
															</th>
														))}
													</tr>
												</thead>
												<tbody>
													{Array(6).fill(
														<tr>
															<td className="border-b py-2 px-3 text-sm">Jane Cooper</td>
															<td className="border-b py-2 px-3 text-sm">Recruiter</td>
															<td className="border-b py-2 px-3 text-sm">jane@microsoft.com</td>
                                                            <td className="border-b py-2 px-3 text-sm">On Pending</td>
															<td className="w-[250px] border-b py-2 px-3">
																<div className="w-full">
                                                                <Listbox value={access} onChange={setAccess}>
                                                                    <Listbox.Button className={"w-full text-left text-sm font-bold border bg-white dark:bg-gray-700 dark:border-gray-600 rounded-normal min-h-[45px]"}>
                                                                        <span className="py-2 px-3 w-[calc(100%-40px)] inline-block">{access.name}</span>
                                                                        <span className="w-[40px] inline-block text-sm border-l dark:border-gray-600 py-2 px-3 text-center">
                                                                            <i className="fa-solid fa-chevron-down"></i>
                                                                        </span>
                                                                    </Listbox.Button>
                                                                    <Transition
                                                                        enter="transition duration-100 ease-out"
                                                                        enterFrom="transform scale-95 opacity-0"
                                                                        enterTo="transform scale-100 opacity-100"
                                                                        leave="transition duration-75 ease-out"
                                                                        leaveFrom="transform scale-100 opacity-100"
                                                                        leaveTo="transform scale-95 opacity-0"
                                                                    >
                                                                        <Listbox.Options
                                                                            className={
                                                                                "absolute right-0 top-[100%] mt-2 w-[250px] rounded-normal bg-white overflow-hidden shadow-normal dark:bg-gray-700"
                                                                            }
                                                                        >
                                                                            {people.map((person,i) => (
                                                                            <Listbox.Option
                                                                                key={i}
                                                                                value={person}
                                                                                className="clamp_1 relative cursor-pointer px-6 py-2 pl-8 text-sm hover:bg-gray-100 dark:hover:bg-gray-900"
                                                                            >
                                                                                {({ selected }) => (
                                                                                    <>
                                                                                        <span className={` ${selected ? "font-bold" : "font-normal"}`}>{person.name}</span>
                                                                                        {selected ? (
                                                                                            <span className="absolute left-3">
                                                                                                <i className="fa-solid fa-check"></i>
                                                                                            </span>
                                                                                        ) : null}
                                                                                    </>
                                                                                )}
                                                                            </Listbox.Option>
                                                                            ))}
                                                                            <div className="border-t py-2 px-8 text-darkGray dark:text-gray-400 dark:border-gray-400 text-[12px]">
                                                                                <p>Access of <b>{access.name}</b> to the following:-</p>
                                                                                <p>
                                                                                - Job Applications
                                                                                </p>
                                                                                <p>
                                                                                - Analytics
                                                                                </p>
                                                                                <p>
                                                                                - Offer Management
                                                                                </p>
                                                                                <p>
                                                                                - Interviews
                                                                                </p>
                                                                            </div>
                                                                        </Listbox.Options>
                                                                    </Transition>
                                                                </Listbox>
																</div>
															</td>
															<td className="border-b py-2 px-3 text-right">
																<input type="checkbox" />
															</td>
														</tr>
													)}
												</tbody>
											</table>
										</div>
                                    </Tab.Panel>
                                    <Tab.Panel>
                                        a
                                    </Tab.Panel>
                                </Tab.Panels>
                            </Tab.Group>
                        </div>
                    </div>
                </div>
            </main>
            <Transition.Root show={addGroups} as={Fragment}>
				<Dialog as="div" className="relative z-40" initialFocus={cancelButtonRef} onClose={setAddGroups}>
					<Transition.Child
						as={Fragment}
						enter="ease-out duration-300"
						enterFrom="opacity-0"
						enterTo="opacity-100"
						leave="ease-in duration-200"
						leaveFrom="opacity-100"
						leaveTo="opacity-0"
					>
						<div className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
					</Transition.Child>

					<div className="fixed inset-0 z-10 overflow-y-auto">
						<div className="flex min-h-full items-end justify-center p-4 text-center sm:items-center">
							<Transition.Child
								as={Fragment}
								enter="ease-out duration-300"
								enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
								enterTo="opacity-100 translate-y-0 sm:scale-100"
								leave="ease-in duration-200"
								leaveFrom="opacity-100 translate-y-0 sm:scale-100"
								leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
							>
								<Dialog.Panel className="relative w-full transform overflow-hidden rounded-[30px] bg-[#FBF9FF] text-left text-black shadow-xl transition-all dark:bg-gray-800 dark:text-white sm:my-8 sm:max-w-2xl">
									<div className="flex items-center justify-between bg-gradient-to-b from-gradLightBlue to-gradDarkBlue px-8 py-3 text-white">
										<h4 className="flex items-center font-semibold leading-none">
											Add Team Member
										</h4>
										<button
											type="button"
											className="leading-none hover:text-gray-700"
											onClick={() => setAddGroups(false)}
										>
											<i className="fa-solid fa-xmark"></i>
										</button>
									</div>
									<div className="p-8 overflow-auto min-h-[80vh]">
                                        <div className="flex flex-wrap -mx-3">
                                            <div className="w-full md:max-w-[50%] px-3 mb-4">
                                                <FormField fieldType="input" inputType="text" label="Name" />
                                            </div>
                                            <div className="w-full md:max-w-[50%] px-3 mb-4">
                                                <FormField fieldType="input" inputType="email" label="Organization Email" required />
                                            </div>
                                        </div>
                                        <FormField fieldType="input" inputType="text" label="Department" />
                                        <div className="mb-4">
                                            <h6 className="font-bold mb-1">Access</h6>
                                            <Listbox value={access} onChange={setAccess}>
                                                <Listbox.Button className={"w-full text-left text-sm font-bold border bg-white dark:bg-gray-700 dark:border-gray-600 rounded-normal min-h-[45px]"}>
                                                    <span className="py-2 px-3 w-[calc(100%-40px)] inline-block">{access.name}</span>
                                                    <span className="w-[40px] inline-block text-sm border-l dark:border-gray-600 py-2 px-3 text-center">
                                                        <i className="fa-solid fa-chevron-down"></i>
                                                    </span>
                                                </Listbox.Button>
                                                <Transition
                                                    enter="transition duration-100 ease-out"
                                                    enterFrom="transform scale-95 opacity-0"
                                                    enterTo="transform scale-100 opacity-100"
                                                    leave="transition duration-75 ease-out"
                                                    leaveFrom="transform scale-100 opacity-100"
                                                    leaveTo="transform scale-95 opacity-0"
                                                >
                                                    <Listbox.Options
                                                        className={
                                                            "absolute right-0 top-[100%] mt-2 w-[250px] rounded-normal bg-white overflow-hidden shadow-normal dark:bg-gray-700"
                                                        }
                                                    >
                                                        {people.map((person,i) => (
                                                        <Listbox.Option
                                                            key={i}
                                                            value={person}
                                                            className="clamp_1 relative cursor-pointer px-6 py-2 pl-8 text-sm hover:bg-gray-100 dark:hover:bg-gray-900"
                                                        >
                                                            {({ selected }) => (
                                                                <>
                                                                    <span className={` ${selected ? "font-bold" : "font-normal"}`}>{person.name}</span>
                                                                    {selected ? (
                                                                        <span className="absolute left-3">
                                                                            <i className="fa-solid fa-check"></i>
                                                                        </span>
                                                                    ) : null}
                                                                </>
                                                            )}
                                                        </Listbox.Option>
                                                        ))}
                                                        <div className="border-t py-2 px-8 text-darkGray dark:text-gray-400 dark:border-gray-400 text-[12px]">
                                                            <p>Access of <b>{access.name}</b> to the following:-</p>
                                                            <p>
                                                            - Job Applications
                                                            </p>
                                                            <p>
                                                            - Analytics
                                                            </p>
                                                            <p>
                                                            - Offer Management
                                                            </p>
                                                            <p>
                                                            - Interviews
                                                            </p>
                                                        </div>
                                                    </Listbox.Options>
                                                </Transition>
                                            </Listbox>
                                        </div>
                                        <div className="text-center">
                                            <Button label="Add" />
                                        </div>
									</div>
								</Dialog.Panel>
							</Transition.Child>
						</div>
					</div>
				</Dialog>
			</Transition.Root>
        </>
    )
}