import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { axiosInstance } from "@/utils";
import { useSession } from "next-auth/react";
import HeaderBar from "@/components/HeaderBar";
import JobCard_2 from "@/components/JobCard-2";
import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import Image from "next/image";
import bulbIcon from "/public/images/icons/bulb.png";
import { axiosInstanceAuth } from "@/pages/api/axiosApi";
import noActivedata from "/public/images/no-data/iconGroup-1.png";
import Link from "next/link";

export default function JobsActive() {
	const [sklLoad] = useState(true)
	const router = useRouter();

	const { data: session } = useSession();

	const [active, setActiveJobs] = useState([]);
	const [token, settoken] = useState("");

	useEffect(() => {
		if (session) {
			settoken(session.accessToken as string);
		} else if (!session) {
			settoken("");
		}
	}, [session]);

	const axiosInstanceAuth2 = axiosInstanceAuth(token);

	useEffect(() => {
		const getActiveJobs = async () => {
			const newDraftedJobs = await axiosInstance.api
				.get("/job/list-job", { headers: { authorization: "Bearer " + session?.accessToken } })
				.then((response) => response.data.map((job: any) => job.jobStatus === "Active" && job))
				.catch((error) => {
					console.log({ error });
					return null;
				});

			setActiveJobs(newDraftedJobs);
		};

		session && getActiveJobs();
	}, [session]);

	return (
		<>
			<Head>
				<title>Active Jobs</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<OrgSideBar />
				<OrgTopBar />
				<div
					id="overlay"
					className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"
				></div>
				<div className="layoutWrap p-4 lg:p-8">
					<div className="rounded-normal bg-white shadow-normal dark:bg-gray-800">
						<div className="border-b py-4">
							<div className="mx-auto w-full max-w-[1100px] px-4">
								<div className="flex flex-wrap items-center justify-start py-2">
									<button
										onClick={() => router.back()}
										className="mr-10 justify-self-start text-darkGray dark:text-gray-400"
									>
										<i className="fa-solid fa-arrow-left text-2xl"></i>
									</button>
									<h2 className="flex items-center text-xl font-bold">
										<div className="mr-4 flex h-[45px] w-[45px] items-center justify-center rounded bg-[#B2E3FF] p-3">
											<Image src={bulbIcon} alt="Active Job" height={20} />
										</div>
										<span>Active Jobs</span>
									</h2>
								</div>
							</div>
						</div>
						<div className="mx-auto w-full max-w-[980px] px-4 py-8">
							<div className="mx-[-15px] flex flex-wrap">
								{
									sklLoad
									?
									active && active.map(
										(job: any, i) => job && (
											<div className="mb-[30px] w-full px-[15px] md:max-w-[50%]" key={i}>
												<JobCard_2
													key={i}
													job={job}
													// handleView={() => {
													// 	router.push("/organization/jobs/active/" + job.refid);
													// }}
													axiosInstanceAuth2={axiosInstanceAuth2}
												/>
											</div>
										)
									)
									:
									Array(4).fill(
										<div className="mb-[30px] w-full px-[15px] md:max-w-[50%]">
											<JobCard_2 sklLoad={true} />
										</div>
									)
								}
							</div>
							<div className="text-center py-8 w-full max-w-[300px] mx-auto">
								<div className="mb-6 p-2">
									<Image src={noActivedata} alt="No Data" width={300} className="w-auto max-w-[200px] max-h-[200px] mx-auto" />
								</div>
								<h5 className="text-lg font-semibold mb-4">No Active Jobs</h5>
								<p className="text-sm text-darkGray mb-2">There are no Active Jobs , Post a New Job to manage active Jobs</p>
								<Link href={'/organization/jobs/create'} className="my-2 min-w-[60px] inline-block rounded py-2 px-3 text-white text-[14px] bg-gradient-to-b from-gradLightBlue to-gradDarkBlue hover:from-gradDarkBlue hover:to-gradDarkBlue">Post a New Job</Link>
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
