import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { axiosInstance } from "@/utils";
import { useSession } from "next-auth/react";
import HeaderBar from "@/components/HeaderBar";
import JobCard from "@/components/JobCard";
import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";

export default function Home() {
	const router = useRouter();

	const { data: session } = useSession();

	const [active, setActiveJobs] = useState([]);

	useEffect(() => {
		const getDraftedJobs = async () => {
			const newDraftedJobs = await axiosInstance.api
				.get("/job/list-job", { headers: { authorization: "Bearer " + session?.accessToken } })
				.then((response) => response.data.map((job: any) => job.jobStatus === "Published" && job))
				.catch((error) => {
					console.log({ error });
					return null;
				});

			setActiveJobs(newDraftedJobs);
		};

		session && getDraftedJobs();
	}, [session]);

	return (
		<>
			<Head>
				<title>Active Jobs</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
                <OrgSideBar />
                <OrgTopBar />
                <div id="overlay" className="hidden bg-[rgba(0,0,0,0.2)] fixed left-0 top-0 z-[9] w-full h-full"></div>
				<div className="layoutWrap p-4 lg:p-8">
					<div className="bg-white dark:bg-gray-800 rounded-normal">
						<HeaderBar title="Active Jobs" handleBack={() => router.back()} />
						{active &&
							active.map(
								(job: any, i) =>
									job && (
										<JobCard
											key={i}
											job={job}
											handleView={() => {
												router.push("/organization/jobs/active/" + job.refid);
											}}
										/>
									)
							)}
					</div>
				</div>
			</main>
		</>
	);
}
