import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import React from "react"
import Masonry, {ResponsiveMasonry} from "react-responsive-masonry"
import banner from '/public/images/career_banner.png'
import userImg from '/public/images/user-image.png'
import gall_1 from '/public/images/gall-1.png'
import gall_2 from '/public/images/gall-2.png'
import gall_3 from '/public/images/gall-3.png'
import gall_4 from '/public/images/gall-4.png'

export default function cancareer() {
    return (
        <>
            <Head>
                <title>Career</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className="py-8">
                <div className="w-full max-w-[1200px] mx-auto px-4">
                    <Image src={banner} alt="Banner" width={1200} height={200} className="rounded-large mb-6 mx-auto" />
                    <div className="w-full max-w-[1100px] mx-auto px-4">
                        <div className="bg-white dark:bg-gray-900 rounded-normal py-4 px-8">
                            <div className="flex flex-wrap mb-3">
                                <div className="w-full md:max-w-[calc(100%/3)] lg:max-w-[calc(100%/4)] xl:max-w-[calc(100%/5)] pr-4 mb-3">
                                    <Image src={userImg} alt="User" width={80} height={80} className="rounded-full object-cover mb-2" />
                                    <p className="font-bold text-sm mb-1">Benin Wilson</p>
                                    <p className="text-sm text-darkGray">Founder and CEO</p>
                                </div>
                                <div className="w-full md:max-w-[calc(100%/3)] lg:max-w-[calc(100%/4)] xl:max-w-[calc(100%/5)] pr-4 mb-3">
                                    <Image src={userImg} alt="User" width={80} height={80} className="rounded-full object-cover mb-2" />
                                    <p className="font-bold text-sm mb-1">Benin Wilson</p>
                                    <p className="text-sm text-darkGray">Founder and CEO</p>
                                </div>
                            </div>
                            <p className="mb-3">
                                <Link href="https//xyz.com" target="_blank" className="text-primary hover:underline">https//xyz.com</Link>
                            </p>
                            <ul className="mb-6 flex flex-wrap items-center list-disc list-inside text-darkGray dark:text-white font-semibold">
                                <li className="mr-3">
                                500 + Employees
                                </li>
                                <li className="mr-3">
                                Tokyo Japan
                                </li>
                                <li className="mr-3">
                                10 Million Funding
                                </li>
                            </ul>
                            <hr className="mb-6" />
                            <article className="text-darkGray mb-6">
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                            </article>
                            <hr className="mb-6" />
                            <div className="mb-6">
                                <h2 className="font-bold text-lg mb-3">Benefits</h2>
                                <ul className="mb-6 list-disc list-inside text-darkGray dark:text-white font-semibold">
                                    <li className="mr-3">
                                    Medical Insurance
                                    </li>
                                    <li className="mr-3">
                                    Quarterly Bonus
                                    </li>
                                    <li className="mr-3">
                                    Meals
                                    </li>
                                </ul>
                            </div>
                            <hr className="mb-6" />
                            <div>
                                <h2 className="font-bold text-lg mb-3">Work Place Culture</h2>
                                <div className="border rounded-large p-6">
                                    <ResponsiveMasonry
                                        columnsCountBreakPoints={{350: 1, 750: 2, 900: 3}}
                                    >
                                        <Masonry>
                                            <Image src={gall_1} alt="Office" className="rounded-normal w-full p-2" />
                                            <Image src={gall_2} alt="Office" className="rounded-normal w-full p-2" />
                                            <Image src={gall_3} alt="Office" className="rounded-normal w-full p-2" />
                                            <Image src={gall_4} alt="Office" className="rounded-normal w-full p-2" />
                                        </Masonry>
                                    </ResponsiveMasonry>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}