import Button from "@/components/Button";
import FormField from "@/components/FormField";
import Logo from "@/components/Logo";
import CandFooter from "@/components/candidate/footer";
import { useCarrierStore } from "@/utils/code";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";

export default function CandSchedule() {
    const orgdetail: any = useCarrierStore((state: { orgdetail: any }) => state.orgdetail);
    const [select, setSelected] = useState(false);
    return(
        <>
            <Head>
                <title>Schedule Interview</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className="py-8">
                <div className="mx-auto w-full max-w-[800px] px-4">
                    <div className="mb-4 text-center">
                        {orgdetail["OrgProfile"] ? (
                            <Image
                                src={
                                    process.env.NODE_ENV === "production"
                                        ? process.env.NEXT_PUBLIC_PROD_BACKEND + orgdetail["OrgProfile"][0]["logo"]
                                        : process.env.NEXT_PUBLIC_DEV_BACKEND + orgdetail["OrgProfile"][0]["logo"]
                                }
                                alt={"Somhako"}
                                width={200}
                                height={200}
                                className="mx-auto max-h-[80px] w-auto"
                            />
                        ) : (
                            <>
                                <Logo width={180} />
                            </>
                        )}
                    </div>
                    <div className="min-h-[400px] rounded-large bg-white p-6 shadow-normal dark:bg-gray-800 md:px-12 md:py-8">
                        <h1 className="mb-6 text-3xl font-bold">
                            Interview Details
                        </h1>
                        <div className="flex flex-wrap -mx-6">
                            <div className="w-full md:max-w-[50%] p-6 flex">
                                <div className="bg-gradient-to-r from-[#5236FF] to-[#85C5FF] rounded w-[30px] h-[30px] flex items-center justify-center text-white text-sm">
                                    <i className="fa-solid fa-user"></i>
                                </div>
                                <div className="pl-6 py-1">
                                    <h6 className="text-darkGray text-lg mb-2">Interviewer</h6>
                                    <p>Adam Smith</p>
                                </div>
                            </div>
                            <div className="w-full md:max-w-[50%] p-6 flex">
                                <div className="bg-gradient-to-r from-[#3CB8FE] to-[#67D2EA] rounded w-[30px] h-[30px] flex items-center justify-center text-white text-sm">
                                    <i className="fa-solid fa-user"></i>
                                </div>
                                <div className="pl-6 py-1">
                                    <h6 className="text-darkGray text-lg mb-2">Event Duration</h6>
                                    <p>30 min</p>
                                </div>
                            </div>
                            <div className="w-full md:max-w-[50%] p-6 flex">
                                <div className="bg-gradient-to-r from-[#FF930F] to-[#FFB45B] rounded w-[30px] h-[30px] flex items-center justify-center text-white text-sm">
                                    <i className="fa-solid fa-user"></i>
                                </div>
                                <div className="pl-6 py-1">
                                    <h6 className="text-darkGray text-lg mb-2">Interview Name</h6>
                                    <p>Software Developer</p>
                                </div>
                            </div>
                            <div className="w-full md:max-w-[50%] p-6 flex">
                                <div className="bg-gradient-to-r from-[#F98442] to-[#FF9090] rounded w-[30px] h-[30px] flex items-center justify-center text-white text-sm">
                                    <i className="fa-solid fa-user"></i>
                                </div>
                                <div className="pl-6 py-1">
                                    <h6 className="text-darkGray text-lg mb-2">Platform</h6>
                                    <p>Google Meet</p>
                                </div>
                            </div>
                        </div>
                        <p className="text-darkGray mb-4">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        <hr className="mb-4" />
                        <div>
                            <h6 className="mb-3 inline-block font-bold">Select Date and Time for Interview</h6>
                            <div className="flex flex-wrap -mx-4 mb-2">
                                <div className="w-[50%] md:max-w-[33.33%] px-4 mb-4">
                                    <label htmlFor="choosedate_1" className="text-sm group cursor-pointer" onClick={(e)=> setSelected(!select)}>
                                        20 July 2023
                                        <input type="text" value={'3:30 pm to 4:00 pm'} id="choosedate_1" readOnly className={`mt-1 w-full cursor-pointer rounded-normal border border-borderColor p-3 text-sm focus:ring-0 focus:shadow-none focus:outline-none ${select ? 'bg-gradDarkBlue text-white' : 'group-hover:bg-gradLightBlue group-hover:text-white'}`} />
                                    </label>
                                </div>
                                <div className="w-[50%] md:max-w-[33.33%] px-4 mb-4">
                                    <label htmlFor="choosedate_1" className="text-sm group cursor-pointer" onClick={(e)=> setSelected(!select)}>
                                        20 July 2023
                                        <input type="text" value={'3:30 pm to 4:00 pm'} id="choosedate_1" readOnly className={`mt-1 w-full cursor-pointer rounded-normal border border-borderColor p-3 text-sm focus:ring-0 focus:shadow-none focus:outline-none ${select ? 'bg-gradDarkBlue text-white' : 'group-hover:bg-gradLightBlue group-hover:text-white'}`} />
                                    </label>
                                </div>
                                <div className="w-[50%] md:max-w-[33.33%] px-4 mb-4">
                                    <label htmlFor="choosedate_1" className="text-sm group cursor-pointer" onClick={(e)=> setSelected(!select)}>
                                        20 July 2023
                                        <input type="text" value={'3:30 pm to 4:00 pm'} id="choosedate_1" readOnly className={`mt-1 w-full cursor-pointer rounded-normal border border-borderColor p-3 text-sm focus:ring-0 focus:shadow-none focus:outline-none ${select ? 'bg-gradDarkBlue text-white' : 'group-hover:bg-gradLightBlue group-hover:text-white'}`} />
                                    </label>
                                </div>
                                <div className="w-[50%] md:max-w-[33.33%] px-4 mb-4">
                                    <label htmlFor="choosedate_1" className="text-sm group cursor-pointer" onClick={(e)=> setSelected(!select)}>
                                        20 July 2023
                                        <input type="text" value={'3:30 pm to 4:00 pm'} id="choosedate_1" readOnly className={`mt-1 w-full cursor-pointer rounded-normal border border-borderColor p-3 text-sm focus:ring-0 focus:shadow-none focus:outline-none ${select ? 'bg-gradDarkBlue text-white' : 'group-hover:bg-gradLightBlue group-hover:text-white'}`} />
                                    </label>
                                </div>
                            </div>
                            <hr className="mb-4" />
                            <FormField fieldType="input" inputType="email" label="Enter your Email Id" />
                            <Button btnType="submit" label="Schedule" />
                        </div>
                    </div>
                </div>
            </main>
            <CandFooter />
        </>
    )
}