/* eslint-disable react-hooks/rules-of-hooks */
import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import React, { useEffect, useState } from "react"
import Masonry, {ResponsiveMasonry} from "react-responsive-masonry"
import { useCarrierId } from "@/utils/code"
import { axiosInstance } from "@/pages/api/axiosApi"
import Button from "@/components/button";
import moment from "moment"
import { useRouter } from "next/router"

export default function cancareer() {
    const router = useRouter();
    const cid = useCarrierId((state) => state.cid)
	const addcid = useCarrierId((state) => state.addcid)
	

    const orgdetail = useCarrierId((state) => state.orgdetail)
	const setorgdetail = useCarrierId((state) => state.setorgdetail)
    const orgfounderdetail = useCarrierId((state) => state.orgfounderdetail)
	const setorgfounderdetail = useCarrierId((state) => state.setorgfounderdetail)
    const orggallerydetail = useCarrierId((state) => state.orggallerydetail)
	const setorggallerydetail = useCarrierId((state) => state.setorggallerydetail)
    const orgjobdetail = useCarrierId((state) => state.orgjobdetail)
	const setorgjobdetail = useCarrierId((state) => state.setorgjobdetail)

    const [odetail, setodetail] = useState([])
    // const [orgdetail, setorgdetail] = useState([])
    // const [orgfounderdetail, setorgfounderdetail] = useState([])
    // const [orggallerydetail, setorggallerydetail] = useState([])
    // const [orgjobdetail, setorgjobdetail] = useState([])


    useEffect(() => {
        addcid(window.location.href.toString().split("/").pop())
    }, [cid, addcid])


	async function loadOrgDetail(carrierID: any) {
		await axiosInstance
        .get(`/organization/get/organisationprofile/carrier/${carrierID}/`)
        .then((res) => {
			setodetail(res.data)
			setorgdetail(res.data["OrgProfile"])
			setorgfounderdetail(res.data["Founder"])
			setorggallerydetail(res.data["Gallery"])
			setorgjobdetail(res.data["Job"])
        })
	}

    // eslint-disable-next-line react-hooks/rules-of-hooks
    useEffect(()=>{
        if(cid && Object.keys(odetail).length === 0){
            loadOrgDetail(cid)
        }
    },[cid,odetail])

    function viewAllJob(){
        router.push(`/organization/${cid}/search-jobs`)
    }

    function viewJob(refid){
        router.push(`/organization/${cid}/job/${refid}/job-detail`)
    }
    
    
    return (
        <>
            <Head>
                <title>Career</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className="py-8">
            
					{odetail && orgdetail && 
					
					orgdetail.map((data,i)=>(
						<>
                        <div className="w-full max-w-[1200px] mx-auto px-4" key={i}>
                            <Image src={`http://127.0.0.1:8000${data['banner']}`} alt="Banner" width={1200} height={200} className="rounded-large mb-6 mx-auto max-h-[200px] object-cover" />
                            <div className="w-full max-w-[1100px] mx-auto px-4">
                                <div className="bg-white dark:bg-gray-900 rounded-normal py-4 px-8">
                                    <div className="flex flex-wrap mb-3">
                                    {orgfounderdetail.map((data,i)=>(
                                        <div className="w-full md:max-w-[calc(100%/3)] lg:max-w-[calc(100%/4)] xl:max-w-[calc(100%/5)] pr-4 mb-3" key={i}>
                                        <Image src={`http://127.0.0.1:8000${data['image']}`} alt="User" width={80} height={80} className="h-[80px] rounded-full object-cover mb-2" />
                                        <p className="font-bold text-sm mb-1">{data['name']}</p>
                                        <p className="text-sm text-darkGray">{data['designation']}</p>
                                        </div>
                                    ))}
                                    </div>
                                    {data['org_Url'] && data['org_Url']!= '' && <p className="mb-3">
                                        <Link href={`${data['org_Url']}`} target="_blank" className="text-primary hover:underline">{data['org_Url']}</Link>
                                    </p>
                                    }
                                    <ul className="mb-6 flex flex-wrap items-center list-disc list-inside text-darkGray dark:text-white font-semibold">
                                        {data['company_Size'] && data['company_Size']!= '' && <li className="mr-3">
                                        {data['company_Size']} Employees 
                                        </li>}
                                        {data['headquarter_Location'] && data['headquarter_Location']!= '' &&<li className="mr-3">
                                        {data['headquarter_Location']}
                                        </li>}
                                        {data['funding_Details'] && data['funding_Details']!= '' && <li className="mr-3">
                                        {data['funding_Details']}
                                        </li>}
                                    </ul>
                                    <hr className="mb-6" />
                                    {data['about_org'] && data['about_org']!= '' && <article className="text-darkGray mb-6">
                                        {data['about_org']}
                                    </article>}
                                    <hr className="mb-6" />
                                    {data['organization_Benefits'] && data['organization_Benefits']!= '' && <div className="mb-6">
                                        <h2 className="font-bold text-lg mb-3">Benefits</h2>
                                        <p>{data['organization_Benefits']}</p>
                                        {/* <ul className="mb-6 list-disc list-inside text-darkGray dark:text-white font-semibold">
                                            <li className="mr-3">
                                            Medical Insurance
                                            </li>
                                            <li className="mr-3">
                                            Quarterly Bonus
                                            </li>
                                            <li className="mr-3">
                                            Meals
                                            </li>
                                        </ul> */}
                                    </div>
                                    }
                                    <hr className="mb-6" />
                                    { orggallerydetail && 
                                    <div>
                                        <h2 className="font-bold text-lg mb-3">Work Place Culture</h2>
                                        <div className="border rounded-large p-6">
                                            <ResponsiveMasonry
                                                columnsCountBreakPoints={{350: 1, 750: 2, 900: 3}}
                                            >
                                                <Masonry>
                                                    {orggallerydetail.map((data, i) => (
                                                        <img
                                                        src={`http://127.0.0.1:8000${data.image}`}
                                                        alt="Office"
                                                        className="rounded-normal w-full p-2"
                                                        key={i}
                                                        />
                                                    ))}
                                                </Masonry>
                                            </ResponsiveMasonry>
                                        </div>
                                    </div>}
                                    <hr className="mb-6" />
                                    { orgjobdetail && 
                                    <div>
                                        <h2 className="font-bold text-lg mb-3">Recent Jobs</h2>
                                        <div className="border rounded-large p-6">
                                        {orgjobdetail.slice(0, 2).map((data,i)=>(
                                            <div className="w-full md:max-w-[50%] px-[7px] mb-[15px]" key={i}>
                                                <div className="h-full bg-white dark:bg-gray-800 rounded-[10px] shadow-normal p-5">
                                                    <h4 className="font-bold text-lg mb-3">{data['job_title']}</h4>
                                                    <ul className="mb-3 flex flex-wrap items-center text-[12px] text-darkGray dark:text-white font-semibold">
                                                        <li className="mr-8">
                                                            <i className="fa-solid fa-location-dot mr-2"></i>
                                                            {data['worktype'] ? data['worktype'] : <>N/A</>}
                                                        </li>
                                                        <li className="mr-8">
                                                            <i className="fa-regular fa-clock mr-2"></i>
                                                            {data['employment_type'] ? data['employment_type'] : <>N/A</>}
                                                        </li>
                                                        <li className="mr-8">
                                                            <i className="fa-solid fa-dollar-sign mr-2"></i>
                                                            {data['currency'] ? data['currency'] : <>N/A</>}
                                                        </li>
                                                    </ul>
                                                    <div className="flex flex-wrap justify-between items-center">
                                                        <div className="mr-4">
                                                            <Button btnStyle="sm" label="View" loader={false} />
                                                        </div>
                                                        <p className="font-bold text-darkGray dark:text-white text-[12px]">{moment(data['publish_date']).fromNow()}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        ))}
                                        <Button btnStyle="sm" label="View All Job" loader={false} btnType="button" handleClick={viewAllJob}/>
                                        </div>
                                    </div>
                                    }
                                </div>
                            </div>
                        </div>





                        </>
						
					))}

            </main>
        </>
    )
}
