import Button from '@/components/button'
import FormField from '@/components/formfield'
import Logo from '@/components/logo'
import Head from 'next/head'
import Link from 'next/link'

export default function Signin() {
    return (
        <>
            <Head>
                <title>Sign In</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main className='py-8'>
                <div className='w-full max-w-[550px] mx-auto px-4'>
                    <div className='text-center mb-4'>
                        <Logo width={180} />
                    </div>
                    <div className='bg-white dark:bg-gray-800 rounded-large shadow-normal min-h-[400px] p-6 md:py-8 md:px-12'>
                        <h1 className='font-bold text-3xl mb-6'>Sign <span className='text-primary'>In</span></h1>
                        <FormField fieldType="input" inputType="email" label="Email" icon={<i className="fa-regular fa-envelope"></i>} required />
                        <FormField fieldType="input" inputType="password" label="Password" />
                        <div className='mb-4 flex flex-wrap items-center justify-between'>
                            <div className='flex items-center'>
                                <label htmlFor="rememberMe" className='text-darkGray'>
                                    <input type="checkbox" id='rememberMe' className='border-lightGray mr-2 mb-1 rounded' />
                                    Remember Me
                                </label>
                            </div>
                            <Link href={'/auth/forgot'} className="text-primary font-bold hover:underline">Forgot Password?</Link>
                        </div>
                        <div className='mb-4'>
                            <Button btnType="submit" label="Sign In" full={true} loader={false} disabled={false} />
                        </div>
                        <p className='text-center text-darkGray'>
                            Not sign up yet ? <Link href={'/auth/signup'} className="text-primary hover:underline font-bold">Create Account</Link>
                        </p>
                    </div>
                </div>
            </main>
        </>
    )
}