import Button from "@/components/button";
import FormField from "@/components/FormField";
import Logo from "@/components/logo";
import { getProviders } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useReducer } from "react";
import { getCsrfToken, signIn } from "next-auth/react";
import { useRouter } from "next/router";

export default function SignIn({ providers }: any) {
	const router = useRouter();

	return (
		<>
			<Head>
				<title>Sign In</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="py-8">
				<div className="mx-auto w-full max-w-[550px] px-4">
					<div className="mb-4 text-center">
						<Logo width={180} />
					</div>
					<div className="min-h-[400px] rounded-large bg-white p-6 shadow-normal dark:bg-gray-800 md:py-8 md:px-12">
						<h1 className="mb-6 text-3xl font-bold">
							Sign <span className="text-primary">In</span>
						</h1>

						<div className="mb-4">
							<Button
								btnType="button"
								label="Candidate"
								full={true}
								loader={false}
								disabled={false}
								handleClick={async () => await router.push("/auth/candidate/signin")}
							/>
							<Button
								btnType="button"
								label="Organization"
								full={true}
								loader={false}
								disabled={false}
								handleClick={() => router.push("/auth/organization/signin")}
							/>
						</div>
						<p className="text-center text-darkGray">
							Not sign up yet ?{" "}
							<Link href={"/auth/signup"} className="font-bold text-primary hover:underline">
								Create Account
							</Link>
						</p>
					</div>
				</div>
			</main>
		</>
	);
}

export async function getServerSideProps(context: any) {
	const providers = await getProviders();
	return {
		props: {
			providers
		}
	};
}
