//@ts-nocheck
import { useJobId,useCarrierId, useSettingsStore, useStore } from "@/utils/code";
import { getProviders } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useReducer, useState } from "react";
import { axiosInstance } from "../../../api/axiosApi";


export default function Home() {
    const router = useRouter();


	const cid = useCarrierId((state) => state.cid)
	const addcid = useCarrierId((state) => state.addcid)
	const jid = useJobId((state) => state.jid)
	const addjid = useJobId((state) => state.addjid)
	const jdata = useJobId((state) => state.jdata)
	const addjdata = useJobId((state) => state.addjdata)
	
    const [odetail, setodetail] = useState([])
    const [orgdetail, setorgdetail] = useState([])
    const [orgfounderdetail, setorgfounderdetail] = useState([])
    const [orggallerydetail, setorggallerydetail] = useState([])
    const [orgjobdetail, setorgjobdetail] = useState([])


    // useEffect(() => {
    //     addcid(window.location.href.toString().split("/").slice(-2, -1)[0])
    // }, [jid, addjid])


	// async function loadOrgDetail(carrierID: any) {
	// 	await axiosInstance
    //     .get(`/organization/get/organisationprofile/carrier/${carrierID}/`)
    //     .then((res) => {
	// 		setodetail(res.data)
	// 		setorgdetail(res.data["OrgProfile"])
	// 		setorgfounderdetail(res.data["Founder"])
	// 		setorggallerydetail(res.data["Gallery"])
	// 		setorgjobdetail(res.data["Job"])
    //     })
	// }

    // useEffect(()=>{
    //     if(cid && Object.keys(odetail).length === 0){
    //         loadOrgDetail(cid)
    //     }
    // },[cid,odetail])

	// useEffect(()=>{
	// 	console.log(typeof odetail)
	// 	console.log(odetail)
	// 	console.log(typeof orgdetail)
	// 	console.log(orgdetail)
	// },[odetail,orgdetail])

    useEffect(()=>{
        console.log(jdata)
    },[jdata])

    useEffect(()=>{
        console.log(jid)
    },[jid])
    

	return (
		<>
			<Head>
				<title>Job Page</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="py-8">
				<div className="md:px-26 mx-auto w-full max-w-[1920px] px-4 lg:px-40">
                <div className="rounded-normal bg-white p-6 m-6 mt-12 shadow-normal dark:bg-gray-800">
				<div className="mx-auto w-full max-w-[1100px]"> 
                <p>Currency : {jdata.currency}</p>
                <p>deadline : {jdata.deadline}</p>
                <p>department : {jdata.department}</p>
                <p>description : {jdata.description}</p>
                <p>education : {jdata.education}</p>
                <p>employment_type : {jdata.employment_type}</p>
                <p>experience : {jdata.experience}</p>
                <p>group_or_division : {jdata.group_or_division}</p>
                <p>industry : {jdata.industry}</p>
                <p>jobSkill : {jdata.jobSkill}</p>
                <p>jobStatus : {jdata.jobStatus}</p>
                <p>job_function : {jdata.job_function}</p>
                <p>job_title : {jdata.job_title}</p>
                <p>location : {jdata.location}</p>
                <p>looking_for : {jdata.looking_for}</p>
                <p>publish_date : {jdata.publish_date}</p>
                <p>refid : {jdata.refid}</p>
                <p>relocation : {jdata.relocation}</p>
                <p>responsibility : {jdata.responsibility}</p>
                <p>timestamp : {jdata.timestamp}</p>
                <p>vacancy : {jdata.vacancy}</p>
                <p>visa : {jdata.visa}</p>
                <p>worktype : {jdata.worktype}</p>
                <br />
                <hr/>
                <br />
                <button className="btn">APPLY</button>
                
				</div>
				</div>
				</div>
			</main>
		</>
	);
}


export async function getServerSideProps(context: any) {
	const providers = await getProviders();
	return {
		props: {
			providers
		}
	};
}