import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import dashboardIcon from "/public/images/icons/dashboard.png";
import integrationIcon from "/public/images/icons/integration.png";
import jobsIcon from "/public/images/icons/jobs.png";
import analyticsIcon from "/public/images/icons/analytics.png";
import vendorsIcon from "/public/images/icons/vendors.png";
import applicantsIcon from "/public/images/icons/applicants.png";
import collectionIcon from "/public/images/icons/collection.png";
import Button from "@/components/button";
import { useRouter } from "next/router";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import { useReducer, useState } from "react";
import JobFormField from "@/components/JobFormField";

const JobActionButton = ({ label, handleClick }: any) => {
	return (
		<button onClick={handleClick} className="rounded-md border px-3 py-2">
			{label}
		</button>
	);
};

export default function Home() {
	const router = useRouter();

	const [index, setIndex] = useState(0);

	const updateFormInfo = (prevForm: any, event: { target: { id: string; value: any } }) => {
		const { id: key, value } = event.target;

		console.log(prevForm);
		return { ...prevForm, [key]: value };
	};

	const [jobForm, dispatch] = useReducer(updateFormInfo, {
		job_title: "",
		job_function: "",
		department: "",
		industry: "",
		group_or_division: "",
		vacancy: "",
		description: "",
		responsibility: "",
		looking_for: "",
		employment_type: "",
		experience: "",
		education: "",
		location: "",
		currency: "",
		relocation: "",
		visa: "",
		worktype: "",
		deadline: "",
		publish_date: ""
	});

	const [formErrors, setFormErrors] = useState<any>({});

	const jobActions = [
		{
			label: "Preview"
		},
		{
			label: "Save as Draft"
		},
		{
			label: "Publish"
		}
	];
	return (
		<>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="py-8">
				<div className="md:px-26 mx-auto w-full max-w-[1920px] lg:px-40">
					<Tabs onSelect={(i, l) => setIndex(i)}>
						<div className="rounded-normal bg-white pt-5 shadow-normal dark:bg-gray-800">
							<div className="mx-auto w-full max-w-[1100px]">
								<div className="-mx-4 flex flex-wrap items-start justify-between p-6 py-2">
									<button onClick={() => router.back()} className="justify-self-start">
										<i className="fa-solid fa-arrow-left pl-4 text-3xl"></i>
									</button>
									<div className="text-2xl font-normal text-slate-600">
										<span>|{" Job Title"}</span>
									</div>
									<div className="flex flex-row items-center justify-between">
										{jobActions.map((action, i) => (
											<JobActionButton label={action.label} key={i} />
										))}
									</div>
								</div>
								<TabList className="mx-10 mt-8 mb-0 flex flex-row justify-between p-3 text-lg text-slate-700">
									<Tab className={index === 0 ? "font-semibold text-secondary " : ""}>Job Details</Tab>
									<Tab>Assessment</Tab>
									<Tab>Team Members</Tab>
									<Tab>Vendors</Tab>
									<Tab>Job Boards</Tab>
								</TabList>
							</div>
						</div>
						<TabPanel>
							<>
								<div className="relative">
									<div className="absolute z-10 rounded-tl-normal rounded-br-normal bg-gradient-to-t from-[#6A67EA] to-[#9290FC] py-6 px-3 text-white shadow-md">
										Job Title and Department
									</div>
									<div className="relative mt-10 rounded-normal bg-white px-3 shadow-normal dark:bg-gray-800">
										<div className="m-10 p-10 pt-24">
											<JobFormField
												fieldType="input"
												inputType="text"
												label="Job Title"
												id="job_title"
												value={jobForm.job_title}
												error={formErrors?.job_title}
												handleChange={dispatch}
											/>
											<div className="-mx-3 flex flex-wrap">
												<div className="mb-4 w-full px-3 md:max-w-[50%]">
													<JobFormField
														fieldType="input"
														inputType="text"
														label="Job Function"
														id="job_function"
														value={jobForm.job_function}
														error={formErrors?.job_function}
														handleChange={dispatch}
													/>
												</div>
												<div className="mb-4 w-full px-3 md:max-w-[50%]">
													<JobFormField
														fieldType="input"
														inputType="text"
														label="Department"
														id="department"
														value={jobForm.department}
														error={formErrors?.department}
														handleChange={dispatch}
													/>
												</div>
											</div>
											<div className="-mx-3 flex flex-wrap">
												<div className="mb-4 w-full px-3 md:max-w-[50%]">
													<JobFormField
														fieldType="input"
														inputType="text"
														label="Industry"
														id="industry"
														value={jobForm.industry}
														error={formErrors?.industry}
														handleChange={dispatch}
													/>
												</div>
												<div className="mb-4 w-full px-3 md:max-w-[50%]">
													<JobFormField
														fieldType="input"
														inputType="text"
														label="Group or Division"
														id="group_or_division"
														value={jobForm.group_or_division}
														error={formErrors?.group_or_division}
														handleChange={dispatch}
													/>
												</div>
											</div>
											<JobFormField
												fieldType="input"
												inputType="number"
												label="Vacancy"
												id="vacancy"
												value={jobForm.vacancy}
												error={formErrors?.vacancy}
												handleChange={dispatch}
											/>
										</div>
									</div>
								</div>
								<div className="relative">
									<div className="absolute z-10 rounded-tl-normal rounded-br-normal bg-gradient-to-t from-[#6A67EA] to-[#9290FC] py-6 px-3 text-white shadow-md">
										Department Information
									</div>
									<div className="relative mt-10 rounded-normal bg-white px-3 shadow-normal dark:bg-gray-800">
										<div className="m-10 p-10 pt-24">
											<JobFormField
												fieldType="textarea"
												inputType="textarea"
												id="description"
												value={jobForm.description}
												error={formErrors?.description}
												handleChange={dispatch}
											/>
										</div>
									</div>
								</div>
								<div className="relative">
									<div className="absolute z-10 rounded-tl-normal rounded-br-normal bg-gradient-to-t from-[#6A67EA] to-[#9290FC] py-6 px-3 text-white shadow-md">
										Your Responsibilities
									</div>
									<div className="relative mt-10 rounded-normal bg-white px-3 shadow-normal dark:bg-gray-800">
										<div className="m-10 p-10 pt-24">
											<JobFormField
												fieldType="textarea"
												inputType="textarea"
												id="responsibilities"
												value={jobForm.responsibilities}
												error={formErrors?.responsibilities}
												handleChange={dispatch}
											/>
										</div>
									</div>
								</div>
							</>
						</TabPanel>
						<TabPanel>
							<h2>Any content 2</h2>
						</TabPanel>
					</Tabs>
				</div>
			</main>
		</>
	);
}
