import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import TeamMembers from "@/components/TeamMembers";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import jobIcon from "/public/images/icons/jobs.png";

export default function ScheduleInterview() {
    const router = useRouter();
    return (
        <>
            <Head>
                <title>Schedule Interview</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <main>
                <OrgSideBar />
                <OrgTopBar />
                <div id="overlay" className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"></div>
                <div className="layoutWrap p-4 lg:p-8">
                    <div className="rounded-normal bg-white shadow-normal dark:bg-gray-800">
						<div className="border-b py-4">
							<div className="mx-auto w-full max-w-[1100px] px-4 flex flex-wrap items-center justify-between">
								<div className="flex flex-wrap items-center justify-start py-2">
									<button
										onClick={() => router.back()}
										className="mr-10 justify-self-start text-darkGray dark:text-white"
									>
										<i className="fa-solid fa-arrow-left text-2xl"></i>
									</button>
									<h2 className="text-xl font-bold">
										<span>Schedule Interview</span>
									</h2>
								</div>
                                <TeamMembers />
							</div>
						</div>
                        <div className="mx-auto w-full max-w-[980px] px-4 py-8">
                            <aside className="flex items-center mb-4">
                                <Image src={jobIcon} alt="Jobs" width={20} className="mr-3 dark:invert" />
                                <h2 className="text-lg font-bold mr-10">
                                    <span>Software Developer</span>
                                </h2>
                                <p className="text-darkGray">
                                    ID-301478
                                </p>
                            </aside>
                            <div className="flex flex-wrap items-center">
                                <label htmlFor="manualSchedule" className="font-bold flex items-center ">
                                    <div className="bg-white">   
                                        <input type="checkbox" id="manualSchedule" />
                                    </div>
                                    Schedule Manually
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}