import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import { Dialog, Tab, Transition } from "@headlessui/react";
import { Fragment, useRef, useState } from "react";
import userIcon from "/public/images/icons/user.png";
import UploadProfile from "@/components/UploadProfile";
import FormField from "@/components/FormField";
import Button from "@/components/Button";
import Link from "next/link";
import boardIcon from "/public/images/board-icon.png";

export default function Profile() {
    const router = useRouter();

    const cancelButtonRef = useRef(null);
	const [addSocial, setAddSocial] = useState(false);
    const [changePass, setChangePass] = useState(false);

    const tabHeading_1 = [
        {
            title: 'Individual Profile'
        },
        {
            title: 'Organization Profile'
        },
        {
            title: 'Groups'
        },
        {
            title: 'User Access'
        }
    ]
    return(
        <>
            <Head>
				<title>Profile</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<OrgSideBar />
				<OrgTopBar />
				<div id="overlay" className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"></div>
				<div className="layoutWrap p-4 lg:p-8">
					<div className="rounded-normal bg-white shadow-normal dark:bg-gray-800">
						<div className="border-b py-4">
                            <div className="w-full max-w-[1100px] mx-auto mb-4 flex flex-wrap items-center justify-start py-2 px-4">
                                <button
                                    onClick={() => router.back()}
                                    className="mr-10 justify-self-start text-darkGray dark:text-gray-400"
                                >
                                    <i className="fa-solid fa-arrow-left text-2xl"></i>
                                </button>
                                <h2 className="text-xl font-bold flex items-center">
                                    <div className="mr-4 flex h-[45px] w-[45px] items-center justify-center rounded bg-[#B2E3FF] p-3">
                                        <Image src={userIcon} alt='Active Job' height={20} />
                                    </div>
                                    <span>Profile</span>
                                </h2>
                            </div>
                            <Tab.Group>
                                <div className={"border-b px-4"}>
                                    <Tab.List className={"w-full max-w-[1030px] mx-auto"}>
                                        {tabHeading_1.map((item, i)=> 
                                        <Tab key={i} as={Fragment}>
                                            {({ selected }) => (
                                                <button
                                                    className={
                                                        "border-b-4 py-3 mx-6 font-semibold focus:outline-none" +
                                                        " " +
                                                        (selected ? "border-primary text-primary" : "border-transparent text-darkGray")
                                                    }
                                                >
                                                    {item.title}
                                                </button>
                                            )}
                                        </Tab>
                                        )}
                                    </Tab.List>
                                </div>
                                <Tab.Panels>
                                    <Tab.Panel className={"w-full max-w-[1030px] mx-auto px-4 py-8"}>
                                        <div className="mb-4">
                                            <UploadProfile note="Supported Formats 2 mb  : Png , Jpeg" />
                                        </div>
                                        <div className="-mx-3 flex flex-wrap">
                                            <div className="mb-4 w-full px-3 md:max-w-[50%]">
                                                <FormField fieldType="input" inputType="text" label="Organization Name" />
                                            </div>
                                            <div className="mb-4 w-full px-3 md:max-w-[50%]">
                                                <FormField fieldType="input" inputType="text" label="Full Name" />
                                            </div>
                                            <div className="mb-4 w-full px-3 md:max-w-[50%]">
                                                <FormField fieldType="input" inputType="number" label="Contact Number" />
                                            </div>
                                            <div className="mb-4 w-full px-3 md:max-w-[50%]">
                                                <FormField fieldType="input" inputType="email" label="Email Address" required />
                                            </div>
                                            <div className="mb-4 w-full px-3 md:max-w-[50%]">
                                                <FormField fieldType="input" inputType="text" label="Title" />
                                            </div>
                                            <div className="mb-4 w-full px-3 md:max-w-[50%]">
                                                <FormField fieldType="input" inputType="text" label="Department" />
                                            </div>
                                        </div>
                                        <hr className="my-4" />
                                        <div>
                                            <div className="flex flex-wrap items-center justify-between">
                                                <h6 className="mb-1 font-bold">
                                                    Add Social Logins
                                                </h6>
                                                <Button btnType="button" btnStyle="iconRightBtn" label="Add" iconRight={(<i className="fa-solid fa-circle-plus"></i>)} handleClick={() => setAddSocial(true)} />
                                            </div>
                                            <div className="flex flex-wrap">
                                                <Link href="#" className="mr-6 mb-4 w-[100px] rounded-normal shadow-highlight relative p-3 text-center bg-lightBlue dark:bg-gray-700">
                                                    <span className="block w-8 h-8 mx-auto mb-1 shadow-normal rounded p-1 bg-white dark:bg-gray-500">
                                                        <i className="fa-brands fa-facebook"></i>
                                                    </span>
                                                    <p className="font-bold text-[12px]">
                                                        Facebook
                                                    </p>
                                                    <button type="button" className="absolute top-[-10px] right-[-10px] text-center rounded-full text-[20px] font-bold text-red-500 dark:text-white">
                                                        <i className="fa-solid fa-circle-xmark"></i>
                                                    </button>
                                                </Link>
                                                <Link href="#" className="mr-6 mb-4 w-[100px] rounded-normal shadow-highlight relative p-3 text-center bg-lightBlue dark:bg-gray-700">
                                                    <span className="block w-8 h-8 mx-auto mb-1 shadow-normal rounded p-1 bg-white dark:bg-gray-500">
                                                        <i className="fa-brands fa-twitter"></i>
                                                    </span>
                                                    <p className="font-bold text-[12px]">
                                                        Twitter
                                                    </p>
                                                    <button type="button" className="absolute top-[-10px] right-[-10px] text-center rounded-full text-[20px] font-bold text-red-500 dark:text-white">
                                                        <i className="fa-solid fa-circle-xmark"></i>
                                                    </button>
                                                </Link>
                                            </div>
                                        </div>
                                        <hr className="my-4" />
                                        <div>
                                            <h6 className="mb-1 font-bold">
                                                Password Settings
                                            </h6>
                                            <Button btnType="button" label="Change Password" handleClick={() => setChangePass(true)} />
                                        </div>
                                    </Tab.Panel>
                                    <Tab.Panel>
                                        jjjjj
                                    </Tab.Panel>
                                </Tab.Panels>
                            </Tab.Group>
						</div>
					</div>
				</div>
			</main>
            <Transition.Root show={addSocial} as={Fragment}>
				<Dialog as="div" className="relative z-40" initialFocus={cancelButtonRef} onClose={setAddSocial}>
					<Transition.Child
						as={Fragment}
						enter="ease-out duration-300"
						enterFrom="opacity-0"
						enterTo="opacity-100"
						leave="ease-in duration-200"
						leaveFrom="opacity-100"
						leaveTo="opacity-0"
					>
						<div className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
					</Transition.Child>

					<div className="fixed inset-0 z-10 overflow-y-auto">
						<div className="flex min-h-full items-end justify-center p-4 text-center sm:items-center">
							<Transition.Child
								as={Fragment}
								enter="ease-out duration-300"
								enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
								enterTo="opacity-100 translate-y-0 sm:scale-100"
								leave="ease-in duration-200"
								leaveFrom="opacity-100 translate-y-0 sm:scale-100"
								leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
							>
								<Dialog.Panel className="relative w-full transform overflow-hidden rounded-[30px] bg-[#FBF9FF] text-left text-black shadow-xl transition-all dark:bg-gray-800 dark:text-white sm:my-8 sm:max-w-lg">
									<div className="flex items-center justify-between bg-gradient-to-b from-gradLightBlue to-gradDarkBlue px-8 py-3 text-white">
										<h4 className="flex items-center font-semibold leading-none">
											Add Social Login
										</h4>
										<button
											type="button"
											className="leading-none hover:text-gray-700"
											onClick={() => setAddSocial(false)}
										>
											<i className="fa-solid fa-xmark"></i>
										</button>
									</div>
									<div className="p-8">
                                        <FormField
                                            fieldType="select"
                                            inputType="text"
                                            label="Choose social media"
                                            singleSelect
                                            options={[
                                                { name: "Facebook" },
                                                { name: "Twitter" }
                                            ]}
                                        />
                                        <FormField
                                            fieldType="input"
                                            inputType="text"
                                            label="Add URL"
                                        />
										<div className="text-center">
											<Button label="Add" />
										</div>
									</div>
								</Dialog.Panel>
							</Transition.Child>
						</div>
					</div>
				</Dialog>
			</Transition.Root>
            <Transition.Root show={changePass} as={Fragment}>
				<Dialog as="div" className="relative z-40" initialFocus={cancelButtonRef} onClose={setChangePass}>
					<Transition.Child
						as={Fragment}
						enter="ease-out duration-300"
						enterFrom="opacity-0"
						enterTo="opacity-100"
						leave="ease-in duration-200"
						leaveFrom="opacity-100"
						leaveTo="opacity-0"
					>
						<div className="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" />
					</Transition.Child>

					<div className="fixed inset-0 z-10 overflow-y-auto">
						<div className="flex min-h-full items-end justify-center p-4 text-center sm:items-center">
							<Transition.Child
								as={Fragment}
								enter="ease-out duration-300"
								enterFrom="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
								enterTo="opacity-100 translate-y-0 sm:scale-100"
								leave="ease-in duration-200"
								leaveFrom="opacity-100 translate-y-0 sm:scale-100"
								leaveTo="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
							>
								<Dialog.Panel className="relative w-full transform overflow-hidden rounded-[30px] bg-[#FBF9FF] text-left text-black shadow-xl transition-all dark:bg-gray-800 dark:text-white sm:my-8 sm:max-w-lg">
									<div className="flex items-center justify-between bg-gradient-to-b from-gradLightBlue to-gradDarkBlue px-8 py-3 text-white">
										<h4 className="flex items-center font-semibold leading-none">
											Change Password
										</h4>
										<button
											type="button"
											className="leading-none hover:text-gray-700"
											onClick={() => setChangePass(false)}
										>
											<i className="fa-solid fa-xmark"></i>
										</button>
									</div>
									<div className="p-8">
                                        <FormField
                                            fieldType="input"
                                            inputType="password"
                                            label="Old Password"
                                            required
                                        />
                                        <FormField
                                            fieldType="input"
                                            inputType="password"
                                            label="New Password"
                                            required
                                        />
                                        <FormField
                                            fieldType="input"
                                            inputType="password"
                                            label="Confirm Password"
                                            required
                                        />
                                        <div className="text-center">
                                            <Button label="Submit" />
                                        </div>
									</div>
								</Dialog.Panel>
							</Transition.Child>
						</div>
					</div>
				</Dialog>
			</Transition.Root>
        </>
    )
}