import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { axiosInstance } from "@/utils";
import { useSession } from "next-auth/react";
import HeaderBar from "@/components/HeaderBar";
import JobCard_2 from "@/components/JobCard-2";
import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import draftedIcon from "/public/images/icons/closed.png";
import Image from "next/image";
import { axiosInstanceAuth } from "@/pages/api/axiosApi";

export default function JobsDrafted() {
	const router = useRouter();

	const { data: session } = useSession();
	const [token, settoken] = useState("");

	useEffect(() => {
		if (session) {
			settoken(session.accessToken as string);
		} else if (!session) {
			settoken("");
		}
	}, [session]);

	const axiosInstanceAuth2 = axiosInstanceAuth(token);

	const [draftedJobs, setDraftedJobs] = useState([]);

	useEffect(() => {
		const getDraftedJobs = async () => {
			const newDraftedJobs = await axiosInstance.api
				.get("/job/list-job", { headers: { authorization: "Bearer " + session?.accessToken } })
				.then((response) => response.data.map((job: any) => job.jobStatus === "Closed" && job))
				.catch((error) => {
					console.log({ error });
					return null;
				});

			setDraftedJobs(newDraftedJobs);
		};

		session && getDraftedJobs();
	}, [session]);

	return (
		<>
			<Head>
				<title>Closed Jobs</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<OrgSideBar />
				<OrgTopBar />
				<div
					id="overlay"
					className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"
				></div>
				<div className="layoutWrap p-4 lg:p-8">
					<div className="rounded-normal bg-white shadow-normal dark:bg-gray-800">
						<div className="border-b py-4">
							<div className="mx-auto w-full max-w-[1100px] px-4">
								<div className="flex flex-wrap items-center justify-start py-2">
									<button
										onClick={() => router.back()}
										className="mr-10 justify-self-start text-darkGray dark:text-gray-400"
									>
										<i className="fa-solid fa-arrow-left text-2xl"></i>
									</button>
									<h2 className="flex items-center text-xl font-bold">
										<div className="mr-4 flex h-[45px] w-[45px] items-center justify-center rounded bg-[#B2E3FF] p-3">
											<Image src={draftedIcon} alt="Drafted Job" height={20} />
										</div>
										<span>Closed Jobs</span>
									</h2>
								</div>
							</div>
						</div>
						<div className="mx-auto w-full max-w-[980px] px-4 py-8">
							<div className="mx-[-15px] flex flex-wrap">
								{draftedJobs &&
									draftedJobs.map(
										(job: any, i) =>
											job && (
												<div className="mb-[30px] w-full px-[15px] md:max-w-[50%]" key={i}>
													<JobCard_2
														key={i}
														job={job}
														// handleView={() => {
														// 	router.push("/organization/jobs/drafted/" + job.refid);
														// }}
														axiosInstanceAuth2={axiosInstanceAuth2}
													/>
												</div>
											)
									)}
							</div>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
