import Head from "next/head";
import React, { useRef, Fragment, useState, useEffect } from "react";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import NoAuthHeader from "@/components/noAuth/NoAuthHeader";
import NoAuthFooter from "@/components/noAuth/NoAuthFooter";
import landingPageBackground from "public/images/noAuth/landingPageBackground.jpg";
import Image from "next/image";
import Tilt from "react-parallax-tilt";
import overlay1 from "public/images/noAuth/overlay1.png";
import overlay2 from "public/images/noAuth/overlay2.png";
import novusBg from "public/images/noAuth/novusBg.png";
import novusBg1 from "public/images/noAuth/novusBg-full.png";
import bgFinal from "public/images/noAuth/bgFinal.png";
import benfitsImg1 from "public/images/noAuth/benfitsImg1.png";
import novusSection from "public/images/noAuth/novusSection.png";
import whySomhako from "public/images/noAuth/whySomhako.png";
import whySomhako1 from "public/images/noAuth/whySomhako1.png";
import whySomhako2 from "public/images/noAuth/whySomhako2.png";
import whySomhako3 from "public/images/noAuth/whySomhako3.png";
import whySomhako4 from "public/images/noAuth/whySomhako4.png";
import dream1 from "public/images/noAuth/dream1.png";
import faq from "public/images/noAuth/faq.png";
import tab1 from "public/images/noAuth/tab1.png";
import tab2 from "public/images/noAuth/tab2.png";
import tab3 from "public/images/noAuth/tab3.png";
import demoBg from "public/images/noAuth/demoBg.png";
import { Tab, Dialog, Listbox, Transition } from "@headlessui/react";
import { Disclosure } from "@headlessui/react";
import Tabs from "@/components/noAuth/Tabs";
import Faq from "@/components/noAuth/FaQ";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { axiosInstance } from "./api/axiosApi";
import Link from "next/link";
import Button from "@/components/Button";

export default function BlogsPage() {
	const [scrollTop, setScrollTop] = useState(0);

	const handleScroll = (event) => {
		setScrollTop(event.currentTarget.scrollTop);
	};

	useEffect(() => {
		console.log("scrollTop", scrollTop);
	}, [scrollTop]);

	const [state, setState] = useState([]);

	async function loadBlogs(mediumURL: any) {
		await axiosInstance
			.get(mediumURL)
			.then((response) => {
				setState(response.data.items);
			})
			.catch((error) => {
				setState((prevState) => ({
					...prevState,
					error: error.toJSON()
				}));
				console.log(error);
			});
	}

	useEffect(() => {
		const mediumURL = "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@somhako";
		loadBlogs(mediumURL);
	}, []);

	useEffect(() => {
		console.log("!!!", state);
	}, [state]);

	return (
		<>
			<Head>
				<title>Novus ATS</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<NoAuthHeader scrollTop={scrollTop} />
				<div
					id="overlay"
					className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"
				></div>

				<div className="h-[100vh] w-[100vw] overflow-y-scroll" onScroll={handleScroll}>
					{/* hero section */}
					<div
						className="h-auto min-h-[60vh] w-full border-t-2 border-transparent max-md:min-h-[40vh]"
						style={{
							background: "linear-gradient(70deg, #2D129A -5.44%, #47BBFD 120.58%)"
						}}
					>
						<div className="mt-[4rem] flex h-auto min-h-[calc(60vh-4rem)] w-full flex-col items-center justify-start gap-2 p-8 pb-[4rem] max-lg:p-4 max-md:min-h-[calc(40vh-4rem)] max-md:gap-10 max-md:p-2">
							<div className="w-full text-center text-[6vw] font-bold text-black/[0.05] max-lg:text-[7vw] max-md:text-[10vw]">
								Editorial
							</div>
							{/* <div className="flex h-auto w-[80vw] flex-row flex-wrap items-center justify-center gap-8 p-4 px-12 max-lg:h-auto max-lg:min-h-fit max-lg:w-[90vw] max-md:flex-col max-md:p-2">
								{state &&
									state.length > 0 &&
									state.map((data, i) => (
										<div className="m-3 h-96 w-72 rounded-xl bg-white shadow-md" key={i}>
											<div className="h-4/5 w-full">
												<Image
													width={1000}
													height={1000}
													className="h-full w-full rounded-t-xl object-cover"
													src={data.thumbnail}
													alt="piña"
												/>
											</div>
											<div className="h-1/2 w-full p-3">
												<p className="cursor-pointer truncate  text-black hover:text-[#2D129A]">{data.title}</p>
												<Link href={data.link} target="_blank" className="text-[#2D129A] hover:underline">
													read more
												</Link>
											</div>
										</div>
									))}
							</div> */}
						</div>
					</div>
					<div className="h-auto w-full bg-[#F5F6F8]">
						<div className="flex h-auto w-full flex-col items-center justify-start gap-2 p-8  max-lg:p-4 max-md:gap-10 max-md:p-2">
							<div className="mt-[-16rem] flex h-auto w-[60vw] flex-row flex-wrap items-center justify-center gap-8 rounded bg-white p-4 px-12 shadow-lg  max-lg:h-auto max-lg:min-h-fit max-lg:w-[90vw] max-md:mt-[-8rem] max-md:flex-col max-md:p-2">
								{state &&
									state.length > 0 &&
									state.map((data, i) => (
										<div
											className="mx-auto flex w-full cursor-pointer flex-col items-center space-y-3 rounded-xl border border-white bg-white p-3 shadow-lg hover:shadow-xl md:max-w-3xl md:space-x-5 md:space-y-0 md:odd:flex-row md:even:flex-row-reverse"
											key={i}
											onClick={() => {
												window.open(data.link, "_blank");
											}}
										>
											<div className="h-auto w-[40%] max-md:w-full">
												<Image
													src={data.thumbnail}
													alt="why"
													width={500}
													height={500}
													className="ml-auto h-[30vh] w-full object-cover max-md:mx-auto max-md:h-full"
												/>
											</div>

											<div className="flex h-full w-[60%] flex-col space-y-2 bg-white p-3 max-md:w-full">
												{/* <div className="item-center flex justify-between">
													<p className="hidden font-medium text-gray-500 md:block">Vacations</p>
													<div className="flex items-center">
														<svg
															xmlns="http://www.w3.org/2000/svg"
															className="h-5 w-5 text-yellow-500"
															viewBox="0 0 20 20"
															fill="currentColor"
														>
															<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
														</svg>
														<p className="ml-1 text-sm font-bold text-gray-600">
															4.96
															<span className="font-normal text-gray-500">(76 reviews)</span>
														</p>
													</div>
													<div className="">
														<svg
															xmlns="http://www.w3.org/2000/svg"
															className="h-5 w-5 text-pink-500"
															viewBox="0 0 20 20"
															fill="currentColor"
														>
															<path
																fill-rule="evenodd"
																d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
																clip-rule="evenodd"
															/>
														</svg>
													</div>
													<div className="hidden rounded-full bg-gray-200 px-3 py-1 text-xs font-medium text-gray-800 md:block">
														Superhost
													</div>
												</div> */}
												<h3 className="w-[100%] truncate text-xl font-semibold text-gray-800 md:text-2xl">
													{data.title}
												</h3>
												<Link href={data.link} target="_blank" className="text-[#2D129A] hover:underline">
													read more
												</Link>
											</div>
										</div>
									))}

								{/* <div className="relative mx-auto flex max-w-xs flex-col space-y-3 rounded-xl border border-white bg-white p-3 shadow-lg md:max-w-3xl md:flex-row-reverse md:space-x-5 md:space-y-0">
									<div className="grid w-full place-items-center bg-white md:w-1/3">
										<img
											src="https://images.pexels.com/photos/4381392/pexels-photo-4381392.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"
											alt="tailwind logo"
											className="rounded-xl"
										/>
									</div>
									<div className="flex w-full flex-col space-y-2 bg-white p-3 md:w-2/3">
										<div className="item-center flex justify-between">
											<p className="hidden font-medium text-gray-500 md:block">Vacations</p>
											<div className="flex items-center">
												<svg
													xmlns="http://www.w3.org/2000/svg"
													className="h-5 w-5 text-yellow-500"
													viewBox="0 0 20 20"
													fill="currentColor"
												>
													<path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
												</svg>
												<p className="ml-1 text-sm font-bold text-gray-600">
													4.96
													<span className="font-normal text-gray-500">(76 reviews)</span>
												</p>
											</div>
											<div className="">
												<svg
													xmlns="http://www.w3.org/2000/svg"
													className="h-5 w-5 text-pink-500"
													viewBox="0 0 20 20"
													fill="currentColor"
												>
													<path
														fill-rule="evenodd"
														d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z"
														clip-rule="evenodd"
													/>
												</svg>
											</div>
											<div className="hidden rounded-full bg-gray-200 px-3 py-1 text-xs font-medium text-gray-800 md:block">
												Superhost
											</div>
										</div>
										<h3 className="text-xl font-black text-gray-800 md:text-3xl">The Majestic and Wonderful Bahamas</h3>
										<p className="text-base text-gray-500 md:text-lg">
											The best kept secret of The Bahamas is the country’s sheer size and diversity. With 16 major
											islands, The Bahamas is an unmatched destination
										</p>
										<p className="text-xl font-black text-gray-800">
											$110
											<span className="text-base font-normal text-gray-600">/night</span>
										</p>
									</div>
								</div> */}

								{/* {state &&
									state.length > 0 &&
									state.map((data, i) => (
										<div className="m-3 h-96 w-72 rounded-xl bg-white shadow-md" key={i}>
											<div className="h-4/5 w-full">
												<Image
													width={1000}
													height={1000}
													className="h-full w-full rounded-t-xl object-cover"
													src={data.thumbnail}
													alt="piña"
												/>
											</div>
											<div className="h-1/2 w-full p-3">
												<p className="cursor-pointer truncate  text-black hover:text-[#2D129A]">{data.title}</p>
												<Link href={data.link} target="_blank" className="text-[#2D129A] hover:underline">
													read more
												</Link>
											</div>
										</div>
									))} */}
							</div>
						</div>
					</div>

					<NoAuthFooter />
				</div>
			</main>
		</>
	);
}

export async function getStaticProps({ context, locale }: any) {
	const translations = await serverSideTranslations(locale, ["common"]);
	return {
		props: {
			...translations
		}
	};
}

BlogsPage.noAuth = true;
BlogsPage.mobileEnabled = true;
