import Head from "next/head";
import React, { useRef, Fragment, useState, useEffect } from "react";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import NoAuthHeader from "@/components/noAuth/NoAuthHeader";
import NoAuthFooter from "@/components/noAuth/NoAuthFooter";
import landingPageBackground from "public/images/noAuth/landingPageBackground.jpg";
import Image from "next/image";
import Tilt from "react-parallax-tilt";
import overlay1 from "public/images/noAuth/overlay1.png";
import overlay2 from "public/images/noAuth/overlay2.png";
import novusBg from "public/images/noAuth/novusBg.png";
import novusBg1 from "public/images/noAuth/novusBg-full.png";
import bgFinal from "public/images/noAuth/bgFinal.png";
import benfitsImg1 from "public/images/noAuth/benfitsImg1.png";
import novusSection from "public/images/noAuth/novusSection.png";
import whySomhako from "public/images/noAuth/whySomhako.png";
import whySomhako1 from "public/images/noAuth/whySomhako1.png";
import whySomhako2 from "public/images/noAuth/whySomhako2.png";
import whySomhako3 from "public/images/noAuth/whySomhako3.png";
import whySomhako4 from "public/images/noAuth/whySomhako4.png";
import dream1 from "public/images/noAuth/dream1.png";
import faq from "public/images/noAuth/faq.png";
import tab1 from "public/images/noAuth/tab1.png";
import tab2 from "public/images/noAuth/tab2.png";
import tab3 from "public/images/noAuth/tab3.png";
import demoBg from "public/images/noAuth/demoBg.png";
import { Tab, Dialog, Listbox, Transition } from "@headlessui/react";
import { Disclosure } from "@headlessui/react";
import Tabs from "@/components/noAuth/Tabs";
import Faq from "@/components/noAuth/FaQ";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { axiosInstance } from "./api/axiosApi";
import Link from "next/link";
import Button from "@/components/Button";

export default function BlogsPage() {
	const [scrollTop, setScrollTop] = useState(0);

	const handleScroll = (event) => {
		setScrollTop(event.currentTarget.scrollTop);
	};

	useEffect(() => {
		console.log("scrollTop", scrollTop);
	}, [scrollTop]);

	const [state, setState] = useState([]);

	async function loadBlogs(mediumURL: any) {
		await axiosInstance
			.get(mediumURL)
			.then((response) => {
				setState(response.data.items);
			})
			.catch((error) => {
				setState((prevState) => ({
					...prevState,
					error: error.toJSON()
				}));
				console.log(error);
			});
	}

	useEffect(() => {
		const mediumURL = "https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@somhako";
		loadBlogs(mediumURL);
	}, []);

	useEffect(() => {
		console.log("!!!", state);
	}, [state]);

	return (
		<>
			<Head>
				<title>Novus ATS</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<NoAuthHeader scrollTop={scrollTop} />
				<div
					id="overlay"
					className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"
				></div>

				<div className="h-[100vh] w-[100vw] overflow-y-scroll" onScroll={handleScroll}>
					{/* hero section */}
					<div
						className="h-auto min-h-[100vh] w-full border-t-2 border-transparent"
						style={{
							background: "linear-gradient(70deg, #2D129A -5.44%, #47BBFD 120.58%)"
						}}
					>
						<div className="mt-[4rem] flex h-auto min-h-[calc(100vh-4rem)] w-full flex-col items-center justify-start gap-2 p-8 pb-[4rem] max-lg:p-4 max-md:gap-10 max-md:p-2">
							<div className="w-full text-center text-[6vw] font-bold text-black/[0.05] max-lg:text-[5vw] max-md:text-[5vw]">
								Blogs
							</div>
							<div className="flex h-auto w-[80vw] flex-row flex-wrap items-center justify-center gap-8 p-4 px-12 max-lg:h-auto max-lg:min-h-fit max-lg:w-[90vw] max-md:flex-col max-md:p-2">
								{state &&
									state.length > 0 &&
									state.map((data, i) => (
										<div className="m-3 h-96 w-72 rounded-xl bg-white shadow-md" key={i}>
											<div className="h-4/5 w-full">
												<Image
													width={1000}
													height={1000}
													className="h-full w-full rounded-t-xl object-cover"
													src={data.thumbnail}
													alt="piña"
												/>
											</div>
											<div className="h-1/2 w-full p-3">
												<p className="cursor-pointer truncate  text-black hover:text-[#2D129A]">{data.title}</p>
												<Link href={data.link} target="_blank" className="text-[#2D129A] hover:underline">
													read more
												</Link>
											</div>
										</div>
									))}
							</div>
						</div>
					</div>

					<NoAuthFooter />
				</div>
			</main>
		</>
	);
}

export async function getStaticProps({ context, locale }: any) {
	const translations = await serverSideTranslations(locale, ["common"]);
	return {
		props: {
			...translations
		}
	};
}

BlogsPage.noAuth = true;
BlogsPage.mobileEnabled = true;
