import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import dashboardIcon from '/public/images/icons/dashboard.png'

export default function Home() {
  const quicklinks = [
    {
      name: 'Dashboard',
      icon: dashboardIcon
    },
    {
      name: 'Integration',
      icon: dashboardIcon
    },
    {
      name: 'Jobs',
      icon: dashboardIcon
    },
    {
      name: 'Analytics',
      icon: dashboardIcon
    },
    {
      name: 'Vendors',
      icon: dashboardIcon
    },
    {
      name: 'Applicants',
      icon: dashboardIcon
    },
    {
      name: 'Offer Management',
      icon: dashboardIcon
    }
  ]
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='py-8'>
        <div className='lg:px-40 md:px-26 px-4 w-full max-w-[1920px] mx-auto'>
          <div className='bg-white dark:bg-gray-800 rounded-normal shadow-normal p-6'>
            <div className='w-full max-w-[1100px] mx-auto'>
              <div className='flex flex-wrap items-center -mx-4'>
                {quicklinks.map((links, i) => (
                  <div className='w-full md:max-w-[50%] lg:max-w-[33.33%] px-4 mb-8'>
                    <Link key={i} href="#" className='w-full block p-6 bg-white dark:bg-gray-700 dark:hover:bg-gray-600 hover:bg-lightBlue shadow-normal rounded-normal flex items-center'>
                      <div className="mr-4 rounded bg-[#B2E3FF] w-[45px] h-[45px] flex items-center justify-center">
                        <Image src={links.icon} alt={links.name} width={25} height={25} />
                      </div>
                      <span className='font-bold text-lg'>{links.name}</span>
                    </Link>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
