import Head from "next/head";
import React, { useRef, Fragment, useState, useEffect } from "react";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import NoAuthHeader from "@/components/noAuth/NoAuthHeader";

export default function LandingPage() {
	return (
		<>
			<Head>
				<title>Landing Page ATS</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<NoAuthHeader />
				<div
					id="overlay"
					className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"
				></div>
				<div className="scroll-container">
					<section className="scroll-container-child h-[100vh] bg-[#905bd0] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="scroll-container-child h-[100vh] bg-[#3700b3] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="scroll-container-child h-[100vh] bg-[#444cf7] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="scroll-container-child h-[100vh] bg-[#905bd0] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="scroll-container-child h-[100vh] bg-[#3700b3] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="scroll-container-child h-[100vh] bg-[#444cf7] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
				</div>

				{/* <section className="container123">
					<h1 className="child123">Slide 1</h1>
					<h1 className="child123">Slide 2</h1>
					<h1 className="child123">Slide 3</h1>
					<h1 className="child123">Slide 4</h1>
					<h1 className="child123">Slide 5</h1>
				</section> */}
			</main>
		</>
	);
}

export async function getStaticProps({ context, locale }: any) {
	const translations = await serverSideTranslations(locale, ["common"]);
	return {
		props: {
			...translations
		}
	};
}

LandingPage.noAuth = true;
