import Head from "next/head";
import React, { useRef, Fragment, useState, useEffect } from "react";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import NoAuthHeader from "@/components/noAuth/NoAuthHeader";
import landingPageBackground from "public/images/noAuth/landingPageBackground.jpg";
import Image from "next/image";
import Tilt from "react-parallax-tilt";
import bg1x from "public/images/noAuth/bg1x.png";

export default function LandingPage() {
	const [scrollTop, setScrollTop] = useState(0);

	const handleScroll = (event) => {
		setScrollTop(event.currentTarget.scrollTop);
	};

	useEffect(() => {
		console.log("scrollTop", scrollTop);
	}, [scrollTop]);

	return (
		<>
			<Head>
				<title>Landing Page ATS</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<NoAuthHeader scrollTop={scrollTop} />
				<div
					id="overlay"
					className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"
				></div>
				<div
					className="snap-p-2.5 h-[100vh] snap-y snap-proximity snap-always overflow-y-scroll"
					onScroll={handleScroll}
				>
					<section className="relative flex h-[100vh] snap-center flex-col items-center justify-center gap-2 p-4 pt-[65px]">
						<div className="absolute left-0 top-0">
							<Image
								src={landingPageBackground}
								alt="LP"
								width={"1000"}
								height={"1000"}
								className="h-[100vh] w-[100vw] object-cover"
							/>
						</div>
						<div className="z-10 flex max-h-[80vh] w-full shrink items-center justify-between ">
							<div className="w-[50%] ">LOREM1</div>
							<div className="ml-auto w-[50%] ">
								<Image src={bg1x} alt="bg1x" width={1000} height={1000} className="h-auto max-h-[70vh] w-auto" />
							</div>
						</div>
						<div className="cards z-10 grid grid-cols-2 max-sm:cursor-none  max-sm:grid-cols-1 xl:grid-cols-4">
							<div className="card group">
								<p className="px-1 text-xl font-semibold tracking-wide group-hover:font-bold">
									All New AI HR assistant
								</p>
								<p className="px-1.5 text-xs">
									Experience seamless and efficient HR operations with our dedicated, all-new HR assistant powered by
									GPT-4
								</p>
							</div>

							<div className="card group">
								<p className="px-1 text-xl font-semibold tracking-wide group-hover:font-bold">Offer Management</p>
								<p className="px-2.5 text-xs">
									Effortlessly track and manage all your offers with our integrated Offer Management System
								</p>
							</div>
							<div className="card group">
								<p className="px-1 text-xl font-semibold tracking-wider group-hover:font-bold">
									AI generated Job description
								</p>
								<p className="px-5 text-xs">
									Craft comprehensive job descriptions effortlessly and in no time with the help of AI
								</p>
							</div>
							<div className="card group">
								<p className="px-1 text-xl font-semibold tracking-wide group-hover:font-bold">Internal Collaboration</p>
								<p className="px-5 text-xs">
									Utilize our built-in chat feature for seamless and efficient communication
								</p>
							</div>
						</div>
					</section>

					<section className="flex h-[100vh] snap-center items-center justify-center gap-2 bg-[#3700b3] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="flex h-[100vh] snap-center items-center justify-center gap-2 bg-[#444cf7] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="flex h-[100vh] snap-center items-center justify-center gap-2 bg-[#905bd0] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="flex h-[100vh] snap-center items-center justify-center gap-2 bg-[#3700b3] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
					<section className="flex h-[100vh] snap-center items-center justify-center gap-2 bg-[#444cf7] p-4 pt-[65px]">
						Lorem ipsum dolor sit, amet consectetur adipisicing elit. Qui obcaecati labore voluptates dolorum quidem aut
						harum totam sequi magnam molestiae aliquam modi quasi eaque, asperiores libero eos repellat, ipsum pariatur!
					</section>
				</div>

				{/* <section className="container123">
					<h1 className="child123">Slide 1</h1>
					<h1 className="child123">Slide 2</h1>
					<h1 className="child123">Slide 3</h1>
					<h1 className="child123">Slide 4</h1>
					<h1 className="child123">Slide 5</h1>
				</section> */}
			</main>
		</>
	);
}

export async function getStaticProps({ context, locale }: any) {
	const translations = await serverSideTranslations(locale, ["common"]);
	return {
		props: {
			...translations
		}
	};
}

LandingPage.noAuth = true;
