import Head from "next/head";
import React, { useRef, Fragment, useState, useEffect } from "react";
import { useRouter } from "next/router";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import NoAuthHeader from "@/components/noAuth/NoAuthHeader";
import NoAuthFooter from "@/components/noAuth/NoAuthFooter";
import landingPageBackground from "public/images/noAuth/landingPageBackground.jpg";
import Image from "next/image";
import Tilt from "react-parallax-tilt";
import overlay1 from "public/images/noAuth/overlay1.png";
import overlay2 from "public/images/noAuth/overlay2.png";
import novusBg from "public/images/noAuth/novusBg.png";
import novusBg1 from "public/images/noAuth/novusBg-full.png";
import bgFinal from "public/images/noAuth/bgFinal.png";
import benfitsImg1 from "public/images/noAuth/benfitsImg1.png";
import novusSection from "public/images/noAuth/novusSection.png";
import whySomhako from "public/images/noAuth/whySomhako.png";
import novusS1 from "public/images/noAuth/novusS1.png";
import novusA1 from "public/images/noAuth/novusA1.png";
import novusF1 from "public/images/noAuth/novusF1.png";
import novusH1 from "public/images/noAuth/novusH1.png";
import novusH2 from "public/images/noAuth/novusH2.png";
import whySomhako1 from "public/images/noAuth/whySomhako1.png";
import whySomhako2 from "public/images/noAuth/whySomhako2.png";
import whySomhako3 from "public/images/noAuth/whySomhako3.png";
import whySomhako4 from "public/images/noAuth/whySomhako4.png";
import dream1 from "public/images/noAuth/dream1.png";
import faq from "public/images/noAuth/faq.png";
import tab1 from "public/images/noAuth/tab1.png";
import tab2 from "public/images/noAuth/tab2.png";
import tab3 from "public/images/noAuth/tab3.png";
import demoBg from "public/images/noAuth/demoBg.png";
import { Tab, Dialog, Listbox, Transition } from "@headlessui/react";
import { Disclosure } from "@headlessui/react";
import Tabs from "@/components/noAuth/Tabs";
import Faq from "@/components/noAuth/FaQ";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export default function Novus() {
	const settings = {
		dots: false,
		arrows: false,
		infinite: true,
		speed: 1500,
		slidesToShow: 1,
		slidesToScroll: 1,
		adaptiveHeight: false,
		autoplay: true,
		autoplaySpeed: 4000,
		vertical: false,
		emulateTouch: true
	};

	const [scrollTop, setScrollTop] = useState(0);

	const handleScroll = (event) => {
		setScrollTop(event.currentTarget.scrollTop);
	};

	useEffect(() => {
		console.log("scrollTop", scrollTop);
	}, [scrollTop]);

	const whyHeading_1 = [
		{
			title: "Find the best talent with our cutting-edge intelligence technology",
			sub: "Somhako’s AI meticulously curates candidate profiles to enhance your talent pool with our talent insights",
			img: whySomhako1
		},
		{
			title: "Streamline processes and unlock better strategies",
			sub: "Our intuitively designed AI software encourages you to optimise your time by only spending it on things that matter",
			img: whySomhako2
		},
		{
			title: "Explore the potential of our AI integrated platform",
			sub: "Novus acts as your HR assistant to help you deliver the best results by providing a fast-paced environment designed for your ease",
			img: whySomhako3
		},
		{
			title: "Go global with a single click",
			sub: "Somhako’s one-tool dashboard is integrated with multiple languages to ensure global accessibility and utility for all its users",
			img: whySomhako4
		}
	];

	const [disclosures, setDisclosures] = useState([
		{
			id: "disclosure-panel-1",
			isOpen: false,
			buttonText: "Review only the most relevant results",
			panelText:
				"Novus carefully selects and evaluates candidate applications, providing you with ranked results to help you discover the top talents of your industry."
		},
		{
			id: "disclosure-panel-2",
			isOpen: false,
			buttonText: "Experience an elite talent pool",
			panelText:
				"Somhako directs candidates towards the job openings that closely match their strengths so that you can access a strong talent pool that has been hand-picked for your job profile."
		},
		{
			id: "disclosure-panel-3",
			isOpen: false,
			buttonText: "Broaden your network pool",
			panelText:
				"Somhako provides a seamless integration of third-party tools and platforms, thereby enabling collaborations and referral."
		}
	]);

	const handleClick = (id: any) => {
		setDisclosures(disclosures.map((d) => (d.id === id ? { ...d, isOpen: !d.isOpen } : { ...d, isOpen: false })));
	};

	return (
		<>
			<Head>
				<title>Novus ATS</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<NoAuthHeader scrollTop={scrollTop} />
				<div
					id="overlay"
					className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"
				></div>

				<div className="h-[100vh] w-[100vw] overflow-y-scroll" onScroll={handleScroll}>
					{/* hero section */}
					<div
						className="h-auto min-h-[100vh] w-full border-t-2 border-transparent"
						style={{
							background: "linear-gradient(70deg, #2D129A -5.44%, #47BBFD 120.58%)"
						}}
					>
						<div className="mt-[4rem] flex h-auto min-h-[calc(100vh-1rem)] w-full flex-col items-center justify-center gap-20 p-8 max-lg:p-4 max-md:gap-10 max-md:p-2">
							<div className="flex h-auto w-[80vw] flex-row items-center justify-center gap-4 p-4 px-12 max-lg:h-auto max-lg:min-h-fit max-lg:w-[90vw] max-md:flex-col max-md:p-2">
								<div className="h-auto  w-[50%] max-md:w-full">
									<Image
										src={novusH1}
										alt="why"
										width={500}
										height={500}
										className="max-md:min-h-auto ml-auto h-auto max-h-[50vh] w-auto"
									/>
								</div>
								<div className="flex w-[50%] flex-col gap-4 max-md:w-full">
									<div className="w-[70%] text-[2vw] uppercase  text-white max-lg:text-[3.3vw] max-md:w-full max-md:text-center max-md:text-[4vw]">
										Your all new HR Assistant
									</div>
									<div className="w-[60%] text-[1vw] font-light tracking-wider text-white max-lg:text-[2vw] max-md:w-full max-md:text-center max-md:text-[2.5vw]">
										A day’s work done in seconds
									</div>
								</div>
							</div>
							<div className="min-h-auto flex w-[80vw] items-center justify-center gap-4 p-4 px-12 max-lg:h-auto max-lg:min-h-fit max-lg:w-[90vw] max-md:flex-col-reverse max-md:p-2">
								<div className="flex w-[50%]  flex-col gap-4 max-md:w-full">
									<div className="w-[80%]  text-left text-[2vw] uppercase text-white max-lg:w-full  max-lg:text-[3.3vw] max-md:w-full max-md:text-center max-md:text-[4vw]">
										Simplified Resume Screening with a Single-Text Approach
									</div>
									<div className="w-[90%] text-[1vw] font-light tracking-wider text-white max-lg:w-full max-lg:text-[2vw] max-md:w-full max-md:text-center max-md:text-[2.5vw]">
										Novus, driven by AI, provides quick and accurate responses with a single conversation prompt. It
										utilizes an intuitive data-driven method to pre-screen resumes in the talent pool, presenting the
										most relevant candidates ranked by their professional aptitude.
									</div>
									<div className="z-10 flex justify-start  pt-8  text-white max-md:justify-center max-md:pt-4">
										<div
											className="flex w-fit cursor-pointer items-center gap-2 px-3 py-2 text-[1.2vw] max-lg:text-[1.5vw] max-md:text-[2.2vw]"
											style={{
												background: "linear-gradient(88deg, #197DF9 1.75%, #45BBED 103.51%)"
											}}
										>
											<span className=" font-medium tracking-wider">Get Started now</span>
											<i className="fa-regular fa-circle-check "></i>
										</div>
									</div>
								</div>
								<div className="h-auto w-[50%] max-md:w-full">
									<Image
										src={novusH2}
										alt="why"
										width={1000}
										height={1000}
										className="max-md:min-h-auto h-auto max-h-[35vh] w-auto"
									/>
								</div>
							</div>
						</div>
					</div>

					{/* flow section */}
					<div className="flex h-auto w-full items-center justify-center  bg-[#F5F6F8] p-8 max-lg:p-4 max-md:p-2">
						<div className="min-h-auto flex w-[80vw] items-center gap-4  p-4 px-12 max-lg:h-auto max-lg:min-h-fit max-lg:w-[90vw] max-md:flex-col-reverse max-md:p-2">
							<div className="flex w-[50%]  flex-col gap-4 max-md:w-full">
								<div
									className="w-full text-[3vw] font-bold uppercase max-lg:text-[4.3vw] max-md:text-center max-md:text-[5vw]"
									style={{
										background:
											"linear-gradient(75deg, rgba(15, 101, 205, 0.90) -1.16%, rgba(67, 165, 229, 0.63) 108.83%)",
										backgroundClip: "text",
										WebkitBackgroundClip: "text",
										WebkitTextFillColor: "transparent"
									}}
								>
									Flow
								</div>
								<div className="w-[90%] text-[1.5vw] font-medium tracking-wider text-black max-lg:text-[2.3vw] max-md:w-full max-md:text-center max-md:text-[3vw]">
									Source Top Talent and Streamline the Next Steps with Automation
								</div>
								<div className="w-[90%] text-[1vw] font-light tracking-wider text-black max-lg:text-[2vw] max-md:w-full max-md:text-center max-md:text-[2.5vw]">
									Unlock Premium Talent, Streamline Scheduling, and Secure Competitive Offers with Somhako-Novus.
									Maximize Sourcing Excellence for Outstanding Results. Manage a Strong Candidate Pipeline and Drive
									Business Success. Novus automates follow-up emails, reminders, and updates for stress-free
									communication
								</div>
								<div className="z-10 flex justify-start  pt-8 text-white max-md:justify-center max-md:pt-4">
									<div
										className="flex w-fit cursor-pointer items-center gap-2 px-3 py-2 text-[1.2vw] max-lg:text-[1.5vw] max-md:text-[2.2vw]"
										style={{
											background: "linear-gradient(88deg, #197DF9 1.75%, #45BBED 103.51%)"
										}}
									>
										<span className=" font-medium tracking-wider">Get Started now</span>
										<i className="fa-regular fa-circle-check "></i>
									</div>
								</div>
							</div>
							<div className="h-auto w-[50%] max-md:w-full">
								<Image
									src={novusF1}
									alt="why"
									width={1000}
									height={1000}
									className="max-md:min-h-auto h-auto max-h-[50vh] w-auto"
								/>
							</div>
						</div>
					</div>

					{/* analytics section */}
					<div
						className="flex h-auto w-full items-center justify-center   p-8 max-lg:p-4 max-md:p-2"
						style={{
							background: "linear-gradient(70deg, #2D129A -5.44%, #47BBFD 120.58%)"
						}}
					>
						<div className="min-h-auto flex w-[80vw] items-center gap-4  p-4 px-12 max-lg:h-auto max-lg:min-h-fit max-lg:w-[90vw] max-md:flex-col max-md:p-2">
							<div className="h-auto w-[50%] max-md:w-full">
								<Image
									src={novusA1}
									alt="why"
									width={1000}
									height={1000}
									className="max-md:min-h-auto ml-auto h-auto max-h-[70vh] w-auto"
								/>
							</div>
							<div className="flex w-[50%]  flex-col gap-4 max-md:w-full">
								<div className="w-full text-[3vw] uppercase text-white max-lg:text-[4.3vw] max-md:text-center max-md:text-[5vw]">
									Analytics
								</div>
								<div className="w-[90%] text-[1.5vw] font-medium tracking-wider text-white max-lg:text-[2.3vw] max-md:w-full max-md:text-center max-md:text-[3vw]">
									Strategic Recruitment Insights: Monitor Conversions and Optimize Sourcing
								</div>
								<div className="w-[90%] text-[1vw] font-light tracking-wider text-white max-lg:text-[2vw] max-md:w-full max-md:text-center max-md:text-[2.5vw]">
									Efficiently Monitor Source-Specific Candidate Conversions and Identify Trends to Optimize Your
									Recruitment and Sourcing Strategies. Access Essential Data and Analytics for Informed Decision-Making,
									Ensuring Continuous Enhancement and Long-term Success in Your Recruitment Processes
								</div>
								<div className="z-10 flex justify-start  pt-8 text-white max-md:justify-center max-md:pt-4">
									<div
										className="flex w-fit cursor-pointer items-center gap-2 px-3 py-2 text-[1.2vw] max-lg:text-[1.5vw] max-md:text-[2.2vw]"
										style={{
											background: "linear-gradient(88deg, #197DF9 1.75%, #45BBED 103.51%)"
										}}
									>
										<span className=" font-medium tracking-wider">Get Started now</span>
										<i className="fa-regular fa-circle-check "></i>
									</div>
								</div>
							</div>
						</div>
					</div>

					{/* spotlight section */}
					<div
						className="flex h-auto min-h-[35vh] w-full items-center justify-center  px-8 py-0 max-lg:p-4 max-md:p-2"
						style={{
							backgroundImage: "url('images/noAuth/tabBg1.jpg')",
							backgroundRepeat: "no-repeat",
							backgroundSize: "cover",
							backgroundPosition: "center"
						}}
					>
						<div className="min-h-auto flex w-full items-center gap-4  p-4 px-12 max-lg:h-auto max-lg:min-h-fit max-lg:w-[90vw] max-md:flex-col-reverse max-md:p-2">
							<div className="flex w-[50%]  flex-col gap-4 max-md:w-full">
								<div className="w-full text-[1.5vw] font-medium tracking-wider text-white max-lg:text-[2.3vw] max-md:w-full max-md:text-center max-md:text-[3vw]">
									Rapid, Effective, and Improved Hiring with Somhako - Boost Your Recruitment Success!
								</div>
								<div className="z-10 flex justify-start  pt-4 text-white max-md:justify-center max-md:pt-4">
									<div
										className="flex w-fit cursor-pointer items-center gap-2 px-3 py-2 text-[1.2vw] max-lg:text-[1.5vw] max-md:text-[2.2vw]"
										style={{
											background: "linear-gradient(88deg, #197DF9 1.75%, #45BBED 103.51%)"
										}}
									>
										<span className=" font-medium tracking-wider">Get Started now</span>
										<i className="fa-regular fa-circle-check "></i>
									</div>
								</div>
							</div>
							<div className="h-auto w-[50%] max-md:w-full">
								<Image
									src={novusS1}
									alt="why"
									width={1000}
									height={1000}
									className="max-md:min-h-auto mx-auto h-auto max-h-[30vh] w-auto"
								/>
							</div>
						</div>
					</div>

					<NoAuthFooter />
				</div>
			</main>
		</>
	);
}

export async function getStaticProps({ context, locale }: any) {
	const translations = await serverSideTranslations(locale, ["common"]);
	return {
		props: {
			...translations
		}
	};
}

Novus.noAuth = true;
Novus.mobileEnabled = true;
