import Button from "@/components/Button";
import { axiosInstance } from "@/utils";
import { getProviders, useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Logo from "@/components/Logo";
import OrganizationCalendar from "@/components/organization/OrganizationCalendar";
import Header from "@/components/Header";
import axios from "axios";

export default function SignIn({ providers }: any) {
	const router = useRouter();
	const { data: session } = useSession();

	const [calendarIntegrations, setCalendarIntegration] = useState([]);
	const [mailIntegration, setMailIntegration] = useState<any>();

	useEffect(() => {
		async function loadCalendarIntegrations() {
			if (!session) return;

			const { validatedIntegrations: newIntegrations } = await axiosInstance.next_api
				.get("/api/integrations/calendar")
				.then((response) => response.data)
				.catch((err) => {
					console.log(err);
					return { data: { success: false } };
				});

			setCalendarIntegration(newIntegrations);
		}

		async function loadMailIntegrations() {
			if (!session) return;

			const { validatedIntegrations: newIntegrations } = await axiosInstance.next_api
				.get("/api/integrations/mail")
				.then((response) => response.data)
				.catch((err) => {
					console.log(err);
					return { data: { success: false } };
				});

			setMailIntegration(newIntegrations);
		}

		loadCalendarIntegrations();
		loadMailIntegrations();
	}, [router, session]);

	const [to, setTo] = useState("");
	const [subject, setSubject] = useState("");
	const [content, setContent] = useState("");

	useEffect(() => {}, [calendarIntegrations]);

	const createCalendarAuth = async (event: any) => {
		event.preventDefault();
		await router.push("/api/integrations/gcal/create");
	};
	const createGmailAuth = async () => {
		await router.push("/api/integrations/gmail/create");
	};

	const sendMail = async (event: any) => {
		event.preventDefault();
		await axiosInstance.next_api.post("/api/integrations/gmail/sendMail", {
			gmailIntegration: mailIntegration[0],
			message: {
				to,
				subject,
				content
			}
		});
	};
	return (
		<>
			<Head>
				<title>Test</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Header />
			<main className="py-8">
				<form className="mx-auto w-full max-w-[550px] px-4" onSubmit={sendMail}>
					<div className="mb-4 text-center">
						<Logo width={180} />
					</div>
					<div className="min-h-[400px] rounded-large bg-white p-6 shadow-normal dark:bg-gray-800 md:py-8 md:px-12">
						<div className="mb-4">
							<Button
								btnType="button"
								handleClick={async () => await createGmailAuth()}
								label="Get Google Auth"
								full={true}
								loader={false}
								disabled={false}
							/>
						</div>
						{/* <div>
							{integration?.map((integration: any, i) => (
								<Button
									btnType="button"
									full={true}
									loader={false}
									disabled={false}
									key={i}
									label={`Create ${integration.provider.charAt(0).toUpperCase() + integration.provider.slice(1)} Event`}
									handleClick={async () =>
										await axiosInstance.next_api.post("/api/integrations/gcal/createEvent", {
											googleCalendarIntegration: integration
										})
									}
								/>
							))}
						</div> */}
						<div className="mb-4">
							<Button btnType="submit" full={true} loader={false} disabled={false} label={"Test"} />
						</div>
						<div className="mb-4">
							<input
								className="rounded-large bg-white shadow-normal dark:bg-gray-800 "
								placeholder={"To"}
								value={to}
								onChange={(e) => setTo(e.target.value)}
								required
							/>
							<input
								className="rounded-large bg-white shadow-normal dark:bg-gray-800 "
								placeholder={"Subject"}
								value={subject}
								onChange={(e) => setSubject(e.target.value)}
								required
							/>
							<input
								className="rounded-large bg-white shadow-normal dark:bg-gray-800 "
								placeholder={"Content"}
								value={content}
								onChange={(e) => setContent(e.target.value)}
								required
							/>
						</div>
					</div>
				</form>
				<div className="relative w-full transform overflow-hidden rounded-[30px] bg-[#FBF9FF] text-left text-black shadow-xl transition-all dark:bg-gray-800 dark:text-white sm:my-8 sm:max-w-5xl">
					{/* <OrganizationCalendar integration={integration[0]} /> */}
				</div>
			</main>
		</>
	);
}

export async function getServerSideProps(context: any) {
	const providers = await getProviders();
	return {
		props: {
			providers
		}
	};
}
