import OrgSideBar from "@/components/organization/SideBar";
import OrgTopBar from "@/components/organization/TopBar";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import googleIcon from "/public/images/social/google-icon.png";

export default function OrgNotifications() {
    return(
        <>
            <Head>
				<title>Notifications</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<OrgSideBar />
				<OrgTopBar />
				<div id="overlay" className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)] dark:bg-[rgba(255,255,255,0.2)]"></div>
				<div className="layoutWrap p-4 lg:p-8">
                    <div className="bg-white dark:bg-gray-800 border dark:border-gray-600 rounded-normal shadow-normal">
                        <div className="border-b dark:border-gray-600">
                            <div className="w-full max-w-[1100px] mx-auto px-4 py-4">
                                <h1 className="font-bold text-2xl">Notifications</h1>
                            </div>
                        </div>
                        <div className="w-full max-w-[1100px] mx-auto px-4 py-4">
                            <div className="mb-4 last:mb-0 bg-lightBlue dark:bg-gray-600 rounded-normal overflow-hidden">
                                <div className="py-4 px-8 border-b dark:border-gray-500">
                                    <h3 className="font-bold mb-1">Video Interview has been scheduled</h3>
                                    <p className="text-darkGray dark:text-gray-400 text-sm">March 23, 2023 at 6:00 pm</p>
                                </div>
                                <div className="py-4 px-8">
                                    <div className="flex flex-wrap mb-4">
                                        <div className="w-full lg:max-w-[20%] pr-4 mr-4">
                                            <h6 className="font-bold text-sm">Scheduled by</h6>
                                            <p className="text-[12px] text-darkGray dark:text-gray-400">Admin Smith</p>
                                        </div> 
                                        <div className="w-full lg:max-w-[20%] pl-4">
                                            <h6 className="font-bold text-sm">Job ID</h6>
                                            <p className="text-[12px] text-darkGray dark:text-gray-400">54123</p>
                                        </div> 
                                    </div>
                                    <div className="flex flex-wrap mb-4">
                                        <div className="w-full lg:max-w-[20%] pr-4 mr-4 border-r dark:border-gray-500">
                                            <h6 className="font-bold text-sm">Interview Type</h6>
                                            <p className="text-[12px] text-darkGray dark:text-gray-400">Video Interview</p>
                                        </div> 
                                        <div className="w-full lg:max-w-[20%] pl-4">
                                            <div className="flex items-center">
                                                <Image
                                                    src={googleIcon}
                                                    alt="Google"
                                                    width={100}
                                                    className="h-[30px] w-auto rounded-full object-cover"
                                                />
                                                <aside className="pl-3 text-[12px]">
                                                    <h5 className="font-bold text-sm">Google Meet</h5>
                                                    <Link href="www.googlemeet.com" target="_blank" className="text-primary">
                                                        www.googlemeet.com
                                                    </Link>
                                                </aside>
                                            </div>
                                        </div> 
                                    </div>
                                </div>
                            </div>
                            <div className="mb-4 last:mb-0 bg-red-100 rounded-normal overflow-hidden">
                                <div className="py-4 px-8 border-b border-red-200">
                                    <h3 className="font-bold mb-1 dark:text-black">Applicant Profile is <span className="text-red-700">Rejected</span></h3>
                                    <p className="text-darkGray text-sm">March 23, 2023 at 6:00 pm</p>
                                </div>
                                <div className="py-4 px-8">
                                    <div className="flex flex-wrap mb-4">
                                        <div className="w-full lg:max-w-[20%] pr-4 mr-4">
                                            <h6 className="font-bold text-sm dark:text-black">Scheduled by</h6>
                                            <p className="text-[12px] text-darkGray">Admin Smith</p>
                                        </div> 
                                        <div className="w-full lg:max-w-[20%] pl-4">
                                            <h6 className="font-bold text-sm dark:text-black">Job ID</h6>
                                            <p className="text-[12px] text-darkGray">54123</p>
                                        </div> 
                                    </div>
                                </div>
                            </div>  
                            <div className="mb-4 last:mb-0 bg-green-100 rounded-normal overflow-hidden">
                                <div className="py-4 px-8 border-b border-green-200">
                                    <h3 className="font-bold mb-1 dark:text-black">Applicant Profile is <span className="text-green-700">Shortlisted</span></h3>
                                    <p className="text-darkGray text-sm">March 23, 2023 at 6:00 pm</p>
                                </div>
                                <div className="py-4 px-8">
                                    <div className="flex flex-wrap mb-4">
                                        <div className="w-full lg:max-w-[20%] pr-4 mr-4">
                                            <h6 className="font-bold text-sm dark:text-black">Scheduled by</h6>
                                            <p className="text-[12px] text-darkGray">Admin Smith</p>
                                        </div> 
                                        <div className="w-full lg:max-w-[20%] pl-4">
                                            <h6 className="font-bold text-sm dark:text-black">Job ID</h6>
                                            <p className="text-[12px] text-darkGray">54123</p>
                                        </div> 
                                    </div>
                                </div>
                            </div>
                            <div className="mb-4 last:mb-0 bg-lightBlue dark:bg-gray-600 rounded-normal overflow-hidden">
                                <div className="py-4 px-8">
                                    <h3 className="font-bold mb-1">Vendor (Name) has been successfully logged in</h3>
                                    <p className="text-darkGray dark:text-gray-400 text-sm">March 23, 2023 at 6:00 pm</p>
                                </div>
                            </div>
                            <div className="mb-4 last:mb-0 bg-lightBlue dark:bg-gray-600 rounded-normal overflow-hidden">
                                <div className="py-4 px-8">
                                    <h3 className="font-bold mb-1">New Team Member (Name) has been successfully logged in</h3>
                                    <p className="text-darkGray dark:text-gray-400 text-sm">March 23, 2023 at 6:00 pm</p>
                                </div>
                            </div> 
                            <div className="mb-4 last:mb-0 bg-lightBlue dark:bg-gray-600 rounded-normal overflow-hidden">
                                <div className="py-4 px-8 border-b dark:border-gray-500">
                                    <h3 className="font-bold mb-1">Jane Cooper has posted a new job</h3>
                                    <p className="text-darkGray dark:text-gray-400 text-sm">March 23, 2023 at 6:00 pm</p>
                                </div>
                                <div className="py-4 px-8">
                                    <div className="flex flex-wrap mb-4">
                                        <div className="w-full lg:max-w-[20%] pr-4 mr-4">
                                            <h6 className="font-bold text-sm">Scheduled by</h6>
                                            <p className="text-[12px] text-darkGray dark:text-gray-400">Admin Smith</p>
                                        </div> 
                                        <div className="w-full lg:max-w-[20%] pl-4">
                                            <h6 className="font-bold text-sm">Job ID</h6>
                                            <p className="text-[12px] text-darkGray dark:text-gray-400">54123</p>
                                        </div> 
                                    </div>
                                </div>
                            </div> 
                            <div className="mb-4 last:mb-0 bg-lightBlue dark:bg-gray-600 rounded-normal overflow-hidden">
                                <div className="py-4 px-8 border-b dark:border-gray-500">
                                    <h3 className="font-bold mb-1">Applicant has been shifted to Offer Management</h3>
                                    <p className="text-darkGray dark:text-gray-400 text-sm">March 23, 2023 at 6:00 pm</p>
                                </div>
                                <div className="py-4 px-8">
                                    <div className="flex flex-wrap mb-4">
                                        <div className="w-full lg:max-w-[20%] pr-4 mr-4">
                                            <h6 className="font-bold text-sm">Scheduled by</h6>
                                            <p className="text-[12px] text-darkGray dark:text-gray-400">Admin Smith</p>
                                        </div> 
                                        <div className="w-full lg:max-w-[20%] pl-4">
                                            <h6 className="font-bold text-sm">Job ID</h6>
                                            <p className="text-[12px] text-darkGray dark:text-gray-400">54123</p>
                                        </div> 
                                    </div>
                                </div>
                            </div> 
                            <div className="mb-4 last:mb-0 bg-red-100 rounded-normal overflow-hidden">
                                <div className="py-4 px-8 border-b border-red-200">
                                    <h3 className="font-bold mb-1 dark:text-black">Jane Cooper has <span className="text-red-700">Closed</span> a job</h3>
                                    <p className="text-darkGray text-sm">March 23, 2023 at 6:00 pm</p>
                                </div>
                                <div className="py-4 px-8">
                                    <div className="flex flex-wrap mb-4">
                                        <div className="w-full lg:max-w-[20%] pr-4 mr-4">
                                            <h6 className="font-bold text-sm dark:text-black">Scheduled by</h6>
                                            <p className="text-[12px] text-darkGray">Admin Smith</p>
                                        </div> 
                                        <div className="w-full lg:max-w-[20%] pl-4">
                                            <h6 className="font-bold text-sm dark:text-black">Job ID</h6>
                                            <p className="text-[12px] text-darkGray">54123</p>
                                        </div> 
                                    </div>
                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
            </main>
        </>
    )
}