import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import bulbIcon from "/public/images/icons/bulb.png";
import jobsIcon from "/public/images/icons/post-new-job.png";
import draftedIcon from "/public/images/icons/drafted.png";
import folderIcon from "/public/images/icons/folder.png";
import closedIcon from "/public/images/icons/closed.png";
import applicantsIcon from "/public/images/icons/applicants.png";
import { useRouter } from "next/router";
import { axiosInstance } from "@/utils";
import { getToken } from "next-auth/jwt";
import { useSession } from "next-auth/react";
import Orgsidebar from "@/components/organization/SideBar";
import Orgtopbar from "@/components/organization/TopBar";

export default function JobsDashboard() {
	const router = useRouter();

	const { data: session } = useSession();

	const quicklinks = [
		{
			name: "Post New Job",
			icon: jobsIcon,
			link: "/organization/jobs/create"
		},
		{
			name: "Active Jobs",
			icon: bulbIcon,
			link: "/organization/jobs/active"
		},
		{
			name: "Drafted Jobs",
			icon: draftedIcon,
			link: "/organization/jobs/draft"
		},
		{
			name: "Archived Jobs",
			icon: folderIcon,
			link: "/organization/jobs/archived"
		},
		{
			name: "Closed Jobs",
			icon: closedIcon,
			link: "/organization/jobs/closed"
		}
	];

	return (
		<>
			<Head>
				<title>Jobs</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main>
				<Orgsidebar />
				<Orgtopbar />
				<div id="overlay" className="fixed left-0 top-0 z-[9] hidden h-full w-full bg-[rgba(0,0,0,0.2)]"></div>
				<div className="layoutWrap p-4 lg:p-8">
					<div className="relative rounded-normal bg-white p-10 shadow-normal dark:bg-gray-800">
						<h1 className="mb-6 text-2xl font-bold">Jobs</h1>
						<div className="-mx-4 flex flex-wrap items-center">
							{quicklinks.map((links, i) => (
								<div key={i} className="mb-8 w-full px-4 md:max-w-[50%] lg:max-w-[25%]">
									<Link
										href={links.link}
										className="block rounded-normal bg-white p-6 shadow-normal hover:bg-lightBlue dark:bg-gray-700 dark:hover:bg-gray-600"
									>
										<div className="mb-10 flex w-full items-center">
											<div className="mr-4 flex h-[45px] w-[45px] items-center justify-center rounded bg-[#B2E3FF] p-3">
												<Image src={links.icon} alt={links.name} height={20} />
											</div>
											<span className="text-lg font-bold">{links.name}</span>
										</div>
										<span className="flex items-center text-sm text-primary dark:text-gray-300">
											Go To <i className="fa-solid fa-arrow-right ml-2 text-[12px]"></i>
										</span>
									</Link>
								</div>
							))}
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
