import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import dashboardIcon from "/public/images/icons/dashboard.png";
import integrationIcon from "/public/images/icons/integration.png";
import jobsIcon from "/public/images/icons/jobs.png";
import analyticsIcon from "/public/images/icons/analytics.png";
import vendorsIcon from "/public/images/icons/vendors.png";
import applicantsIcon from "/public/images/icons/applicants.png";
import collectionIcon from "/public/images/icons/collection.png";
import Button from "@/components/button";
import { useRouter } from "next/router";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import { useEffect, useReducer, useState } from "react";
import JobFormField from "@/components/JobFormField";
import Validator, { Rules } from "validatorjs";
import { axiosInstance } from "@/utils";
import { useSession } from "next-auth/react";
import HeaderBar from "@/components/HeaderBar";
import JobCard from "@/components/JobCard";

export default function Home() {
	const router = useRouter();

	const { data: session } = useSession();

	const [draftedJobs, setDraftedJobs] = useState([]);

	useEffect(() => {
		const getDraftedJobs = async () => {
			const newDraftedJobs = await axiosInstance.api
				.get("/job/list-job", { headers: { authorization: "Bearer " + session?.accessToken } })
				.then((response) => response.data.map((job: any) => !job.jobStatus))
				.catch((error) => {
					console.log({ error });
					return null;
				});

			setDraftedJobs(newDraftedJobs);
		};

		getDraftedJobs();
	}, [session]);
	return (
		<>
			<Head>
				<title>Home</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<main className="py-8">
				<div className="md:px-26 mx-auto h-full w-full max-w-[1920px] overflow-hidden lg:px-40">
					<HeaderBar title="Drafted Jobs" icon={null} handleBack={() => router.back()} />
					<div className="grid h-screen grid-cols-2 items-center bg-white p-10 dark:bg-gray-800">
						{draftedJobs &&
							draftedJobs.map((job: any, i) => (
								<JobCard
									key={i}
									job={job}
									handleView={() => {
										router.push("/jobs/drafted/" + job.refid);
									}}
								/>
							))}
					</div>
				</div>
			</main>
		</>
	);
}
